ParaMonte Python 3.0.0: paramonte.python.Frozen.Frozen Class Reference
paramonte.python.Frozen.Frozen Class Reference
This is a Python class for generating object instances whose attributes can be frozen upon request to avoid addition of further attributes to the object.
Public Member Functions
def __setattr__ (self, key, value)
Private Member Functions
def _freeze (self)
Private Attributes
_frozen
Static Private Attributes
bool _frozen = False
The scalar Python bool internal attribute that maintains the freezing status of the object of class pm.python.Frozen.
Detailed Description
This is a Python class for generating object instances whose attributes can be frozen upon request to avoid addition of further attributes to the object.
This class does not have a custom constructor.
The freezing of the object attributes is achieved by setting the internal property of the class instance _frozen to True, which is False by default.
Returns
fobj : The output scalar Python object of class pm.python.Frozen.
Possible calling interfaces ⛓
import paramonte as pm
itis = pm.python.Frozen()
Example usage ⛓
#!/usr/bin/env python3
import os
import sys
import numpy as np
srcdir = os.path.dirname(__file__)
os.chdir(srcdir) # Change working directory to source code directory.
sys.path.append(os.path.join(srcdir, "..", "..", "..")) # import paramonte module locally if available.
import paramonte as pm
obj = pm.python.Frozen()
obj.attr1 = 1
obj.attr2 = 2
pm.python.show(obj, "obj")
obj._freeze()
try:
    obj.attr3 = 3
except Exception as err:
    print(str(err))
pm.python.show(obj, "obj")
Example output ⛓
obj.attr1 =
1
obj.attr2 =
2
<paramonte.python.Frozen.Frozen object at 0x148bce60bfa0> is an object of class ``pm.python.Frozen``.
The requested attribute 'attr3' does not exist in the object.
You cannot add new attributes to an object of class ``pm.python.Frozen``.
obj.attr1 =
1
obj.attr2 =
2
obj._frozen =
True
Final Remarks ⛓
If you believe this algorithm or its documentation can be improved, we appreciate your contribution and help to edit this page's documentation and source file on GitHub.
For details on the naming abbreviations, see this page.
For details on the naming conventions, see this page.
This software is distributed under the MIT license with additional terms outlined below.
If you use any parts or concepts from this library to any extent, please acknowledge the usage by citing the relevant publications of the ParaMonte library.
If you regenerate any parts/ideas from this library in a programming environment other than those currently supported by this ParaMonte library (i.e., other than C, C++, Fortran, MATLAB, Python, R), please also ask the end users to cite this original ParaMonte library.
This software is available to the public under a highly permissive license.
Help us justify its continued development and maintenance by acknowledging its benefit to society, distributing it, and contributing to it.
Copyright
Computational Data Science Lab
Author:
Fatemeh Bagheri, May 20 2024, 1:25 PM, NASA Goddard Space Flight Center (GSFC), Washington, D.C.
Amir Shahmoradi, May 16 2016, 9:03 AM, Oden Institute for Computational Engineering and Sciences (ICES), UT Austin
Definition at line 1 of file Frozen.py.
Member Function Documentation
__setattr__()
def paramonte.python.Frozen.Frozen.__setattr__ (self, key, value)
Definition at line 43 of file Frozen.py.
References paramonte.python.Frozen.Frozen.__setattr__(), and paramonte.python.Frozen.Frozen._frozen.
Referenced by paramonte.python.Frozen.Frozen.__setattr__().
_freeze()
def paramonte.python.Frozen.Frozen._freeze (self) private
Definition at line 51 of file Frozen.py.
References paramonte.python.Frozen.Frozen._freeze().
Referenced by paramonte.python.Frozen.Frozen._freeze().
Member Data Documentation
_frozen [1/2]
bool paramonte.python.Frozen.Frozen._frozen = False static private
The scalar Python bool internal attribute that maintains the freezing status of the object of class pm.python.Frozen.
Definition at line 41 of file Frozen.py.
Referenced by paramonte.python.Frozen.Frozen.__setattr__().
_frozen [2/2]
paramonte.python.Frozen.Frozen._frozen private
Definition at line 52 of file Frozen.py.
Referenced by paramonte.python.Frozen.Frozen.__setattr__().
The documentation for this class was generated from the following file:
src/python/main/paramonte/python/Frozen.py