var dir_f4d5c9c44fddccfd00385a6b637bd8ec =
[
    [ "bioinformatics.m", "bioinformatics_8m.html", "bioinformatics_8m" ],
    [ "compiler.m", "compiler_8m.html", "compiler_8m" ],
    [ "Contents.m", "matlab_2_09has_2Contents_8m.html", null ],
    [ "curvefitting.m", "curvefitting_8m.html", "curvefitting_8m" ],
    [ "database.m", "database_8m.html", "database_8m" ],
    [ "econometrics.m", "econometrics_8m.html", "econometrics_8m" ],
    [ "financial.m", "financial_8m.html", "financial_8m" ],
    [ "fuzzy.m", "fuzzy_8m.html", "fuzzy_8m" ],
    [ "gads.m", "gads_8m.html", "gads_8m" ],
    [ "gpucoder.m", "gpucoder_8m.html", "gpucoder_8m" ],
    [ "imageproc.m", "imageproc_8m.html", "imageproc_8m" ],
    [ "map.m", "map_8m.html", "map_8m" ],
    [ "medimage.m", "medimage_8m.html", "medimage_8m" ],
    [ "neuralnet.m", "neuralnet_8m.html", "neuralnet_8m" ],
    [ "optimization.m", "optimization_8m.html", "optimization_8m" ],
    [ "parallel.m", "parallel_8m.html", "parallel_8m" ],
    [ "pde.m", "pde_8m.html", "pde_8m" ],
    [ "reinflearning.m", "reinflearning_8m.html", "reinflearning_8m" ],
    [ "riskman.m", "riskman_8m.html", "riskman_8m" ],
    [ "simbio.m", "simbio_8m.html", "simbio_8m" ],
    [ "statistics.m", "statistics_8m.html", "statistics_8m" ],
    [ "textanal.m", "textanal_8m.html", "textanal_8m" ],
    [ "wavelet.m", "wavelet_8m.html", "wavelet_8m" ]
];