ParaMonte Python 3.0.0: paramonte.os.list Namespace Reference
paramonte.os.list Namespace Reference
Functions
def list ()
Return a list of Python strings containing the names of OS platforms supported by the ParaMonte Python library.
Function Documentation
list()
def paramonte.os.list.list ()
Return a list of Python strings containing the names of OS platforms supported by the ParaMonte Python library.
Returns
names : The output Python string list containing: ["Windows", "Linux", "Darwin"].
Possible calling interfaces ⛓
import paramonte as pm
names = pm.os.list()
Example usage ⛓
#!/usr/bin/env python3
import os
import sys
import numpy as np
srcdir = os.path.dirname(__file__)
os.chdir(srcdir) # Change working directory to source code directory.
sys.path.append(os.path.join(srcdir, "..", "..", "..")) # import paramonte module locally if available.
import paramonte as pm
print('pm.os.list()')
print(pm.os.list())
Example output ⛓
Final Remarks ⛓
If you believe this algorithm or its documentation can be improved, we appreciate your contribution and help to edit this page's documentation and source file on GitHub.
For details on the naming abbreviations, see this page.
For details on the naming conventions, see this page.
This software is distributed under the MIT license with additional terms outlined below.
If you use any parts or concepts from this library to any extent, please acknowledge the usage by citing the relevant publications of the ParaMonte library.
If you regenerate any parts/ideas from this library in a programming environment other than those currently supported by this ParaMonte library (i.e., other than C, C++, Fortran, MATLAB, Python, R), please also ask the end users to cite this original ParaMonte library.
This software is available to the public under a highly permissive license.
Help us justify its continued development and maintenance by acknowledging its benefit to society, distributing it, and contributing to it.
Copyright
Computational Data Science Lab
Author:
Joshua Alexander Osborne, May 21 2024, 11:49 PM, University of Texas at Arlington
Fatemeh Bagheri, May 20 2024, 1:25 PM, NASA Goddard Space Flight Center (GSFC), Washington, D.C.
Amir Shahmoradi, May 16 2016, 9:03 AM, Oden Institute for Computational Engineering and Sciences (ICES), UT Austin
Definition at line 1 of file list.py.
References paramonte.os.list.list().
Referenced by paramonte.lib.mpi.choices.choices(), paramonte.lib.path.dll.dll(), paramonte.sys.path.mpiexec.find.find(), paramonte.lib.mpi.runtime.hydra.hydra(), paramonte.lib.mpi.runtime.isimpi.isimpi(), paramonte.os.list.list(), and paramonte.lib.mpi.runtime.ompi.ompi().