var searchData=
[
  ['cascade_2em_0',['Cascade.m',['../Cascade_8m.html',1,'']]],
  ['choice_2em_1',['choice.m',['../choice_8m.html',1,'']]],
  ['choices_2em_2',['choices.m',['../choices_8m.html',1,'']]],
  ['cite_2em_3',['cite.m',['../cite_8m.html',1,'']]],
  ['clean_2em_4',['clean.m',['../clean_8m.html',1,'']]],
  ['clstypes_2em_5',['clstypes.m',['../clstypes_8m.html',1,'']]],
  ['cold_2em_6',['cold.m',['../cold_8m.html',1,'']]],
  ['colornames_2em_7',['colornames.m',['../colornames_8m.html',1,'']]],
  ['colornames_5fcube_2em_8',['colornames_cube.m',['../colornames__cube_8m.html',1,'']]],
  ['colornames_5fdeltae_2em_9',['colornames_deltaE.m',['../colornames__deltaE_8m.html',1,'']]],
  ['colornames_5fdoc_2em_10',['colornames_doc.m',['../colornames__doc_8m.html',1,'']]],
  ['colornames_5fview_2em_11',['colornames_view.m',['../colornames__view_8m.html',1,'']]],
  ['compiler_2em_12',['compiler.m',['../compiler_8m.html',1,'']]],
  ['contents_2em_13',['Contents.m',['../_09data_2Contents_8m.html',1,'(Global Namespace)'],['../Contents_8m.html',1,'(Global Namespace)'],['../_09web_2Contents_8m.html',1,'(Global Namespace)'],['../_09vis_2Contents_8m.html',1,'(Global Namespace)'],['../_09timing_2Contents_8m.html',1,'(Global Namespace)'],['../_09sys_2Contents_8m.html',1,'(Global Namespace)'],['../_09sys_2_09path_2Contents_8m.html',1,'(Global Namespace)'],['../_09sys_2_09path_2_09mpiexec_2Contents_8m.html',1,'(Global Namespace)'],['../_09sys_2_09bashrc_2Contents_8m.html',1,'(Global Namespace)'],['../_09sys_2_09bash__profile_2Contents_8m.html',1,'(Global Namespace)'],['../_09str_2Contents_8m.html',1,'(Global Namespace)'],['../_09stats_2Contents_8m.html',1,'(Global Namespace)'],['../_09stats_2_09dist_2Contents_8m.html',1,'(Global Namespace)'],['../_09array_2Contents_8m.html',1,'(Global Namespace)'],['../_09geom_2_09ell2_2Contents_8m.html',1,'(Global Namespace)'],['../_09geom_2Contents_8m.html',1,'(Global Namespace)'],['../_09introspection_2Contents_8m.html',1,'(Global Namespace)'],['../_09io_2Contents_8m.html',1,'(Global Namespace)'],['../_09lib_2_09mpi_2Contents_8m.html',1,'(Global Namespace)'],['../_09lib_2_09path_2Contents_8m.html',1,'(Global Namespace)'],['../_09lib_2_09update_2Contents_8m.html',1,'(Global Namespace)'],['../_09stats_2_09hist_2Contents_8m.html',1,'(Global Namespace)'],['../_09lib_2Contents_8m.html',1,'(Global Namespace)'],['../_09math_2_09func_2_09himmelblau_2Contents_8m.html',1,'(Global Namespace)'],['../_09math_2_09func_2Contents_8m.html',1,'(Global Namespace)'],['../_09matlab_2_09has_2Contents_8m.html',1,'(Global Namespace)'],['../_09stats_2_09dist_2_09mvu_2Contents_8m.html',1,'(Global Namespace)'],['../_09stats_2_09dist_2_09mvn_2Contents_8m.html',1,'(Global Namespace)'],['../_09stats_2_09dist_2_09himmelblau_2Contents_8m.html',1,'(Global Namespace)'],['../_09sort_2Contents_8m.html',1,'(Global Namespace)'],['../_09sampling_2Contents_8m.html',1,'(Global Namespace)'],['../_09os_2Contents_8m.html',1,'(Global Namespace)'],['../_09os_2_09is_2Contents_8m.html',1,'(Global Namespace)'],['../_09matlab_2Contents_8m.html',1,'(Global Namespace)'],['../_09matlab_2_09struct_2Contents_8m.html',1,'(Global Namespace)'],['../_09matlab_2_09hashmap_2Contents_8m.html',1,'(Global Namespace)'],['../_09math_2Contents_8m.html',1,'(Global Namespace)']]],
  ['contour_2em_14',['Contour.m',['../_09tile_2Contour_8m.html',1,'(Global Namespace)'],['../_09subplot_2Contour_8m.html',1,'(Global Namespace)'],['../_09plot_2Contour_8m.html',1,'(Global Namespace)'],['../_09cascade_2Contour_8m.html',1,'(Global Namespace)']]],
  ['contour3_2em_15',['Contour3.m',['../_09subplot_2Contour3_8m.html',1,'(Global Namespace)'],['../_09plot_2Contour3_8m.html',1,'(Global Namespace)'],['../_09cascade_2Contour3_8m.html',1,'(Global Namespace)'],['../_09tile_2Contour3_8m.html',1,'(Global Namespace)']]],
  ['contourf_2em_16',['Contourf.m',['../_09tile_2Contourf_8m.html',1,'(Global Namespace)'],['../_09subplot_2Contourf_8m.html',1,'(Global Namespace)'],['../_09cascade_2Contourf_8m.html',1,'(Global Namespace)'],['../_09plot_2Contourf_8m.html',1,'(Global Namespace)']]],
  ['copy_2em_17',['copy.m',['../copy_8m.html',1,'']]],
  ['copyfig_2em_18',['copyfig.m',['../copyfig_8m.html',1,'']]],
  ['cor_2em_19',['Cor.m',['../Cor_8m.html',1,'']]],
  ['corner_2em_20',['Corner.m',['../Corner_8m.html',1,'']]],
  ['cov_2em_21',['Cov.m',['../Cov_8m.html',1,'']]],
  ['credits_2em_22',['credits.m',['../credits_8m.html',1,'']]],
  ['crop_5fborders_2em_23',['crop_borders.m',['../crop__borders_8m.html',1,'']]],
  ['curvefitting_2em_24',['curvefitting.m',['../curvefitting_8m.html',1,'']]]
];
