ParaMonte Python 3.0.0: paramonte.timing.Spinner.Spinner Class Reference
paramonte.timing.Spinner.Spinner Class Reference
This is the base class for generating objects that can display the time spinner on the console.
Public Member Functions
def __init__ (self, tickmarks="|/-\\")
Return a scalar object of class pm.timing.Spinner.
def spin (self, fraction)
Rotate the tick mark of the spinner and display the percentage value of the input fraction.
Public Attributes
tickmarks
The Python string containing the set of characters that represent the passage of time in the spinner.
Private Attributes
_nticks
The Python integer containing the length of tickmarks.
_clock
The Python string containing a sequence of carriage returns (crs) characters that must appear at the beginning of the spinner.
Detailed Description
This is the base class for generating objects that can display the time spinner on the console.
Note
See the documentation of the class constructor.
See below for information on the attributes (properties).
See below for information on the methods.
Final Remarks ⛓
If you believe this algorithm or its documentation can be improved, we appreciate your contribution and help to edit this page's documentation and source file on GitHub.
For details on the naming abbreviations, see this page.
For details on the naming conventions, see this page.
This software is distributed under the MIT license with additional terms outlined below.
If you use any parts or concepts from this library to any extent, please acknowledge the usage by citing the relevant publications of the ParaMonte library.
If you regenerate any parts/ideas from this library in a programming environment other than those currently supported by this ParaMonte library (i.e., other than C, C++, Fortran, MATLAB, Python, R), please also ask the end users to cite this original ParaMonte library.
This software is available to the public under a highly permissive license.
Help us justify its continued development and maintenance by acknowledging its benefit to society, distributing it, and contributing to it.
Copyright
Computational Data Science Lab
Author:
Joshua Alexander Osborne, May 21 2024, 5:39 AM, University of Texas at Arlington
Fatemeh Bagheri, May 20 2024, 1:25 PM, NASA Goddard Space Flight Center (GSFC), Washington, D.C.
Amir Shahmoradi, May 16 2016, 9:03 AM, Oden Institute for Computational Engineering and Sciences (ICES), UT Austin
Definition at line 1 of file Spinner.py.
Constructor & Destructor Documentation
__init__()
def paramonte.timing.Spinner.Spinner.__init__ (self, tickmarks = "|/-\\")
Return a scalar object of class pm.timing.Spinner.
This is the constructor of the class pm.timing.Spinner.
Parameters
[in] tickmarks : The input Python string containing the set of characters that represent the passage of time in the spinner.
(optional, default = "|/-\")
Returns
self : The output scalar object of class pm.timing.Spinner.
Possible calling interfaces ⛓
import paramonte as pm
self = pm.timing.Spinner(tickmarks = tickmarks)
Example usage ⛓
#!/usr/bin/env python3
import os
import sys
import numpy as np
srcdir = os.path.dirname(__file__)
os.chdir(srcdir) # Change working directory to source code directory.
sys.path.append(os.path.join(srcdir, "..", "..", "..")) # import paramonte module locally if available.
import paramonte as pm
print('spinner = pm.timing.Spinner()')
spinner = pm.timing.Spinner()
print('for i in range(10): spinner.spin(i/10.)')
for i in range(10): spinner.spin(i/10.)
Example output ⛓
spinner = pm.timing.Spinner()
for i in range(10): spinner.spin(i/10.)
|  0%
/ 10%
- 20%
\ 30%
| 40%
/ 50%
- 60%
\ 70%
| 80%
/ 90%
Final Remarks ⛓
If you believe this algorithm or its documentation can be improved, we appreciate your contribution and help to edit this page's documentation and source file on GitHub.
For details on the naming abbreviations, see this page.
For details on the naming conventions, see this page.
This software is distributed under the MIT license with additional terms outlined below.
If you use any parts or concepts from this library to any extent, please acknowledge the usage by citing the relevant publications of the ParaMonte library.
If you regenerate any parts/ideas from this library in a programming environment other than those currently supported by this ParaMonte library (i.e., other than C, C++, Fortran, MATLAB, Python, R), please also ask the end users to cite this original ParaMonte library.
This software is available to the public under a highly permissive license.
Help us justify its continued development and maintenance by acknowledging its benefit to society, distributing it, and contributing to it.
Copyright
Computational Data Science Lab
Author:
Fatemeh Bagheri, May 20 2024, 1:25 PM, NASA Goddard Space Flight Center (GSFC), Washington, D.C.
Amir Shahmoradi, May 16 2016, 9:03 AM, Oden Institute for Computational Engineering and Sciences (ICES), UT Austin
Warning
This is an internal hidden class attribute that is inaccessible to the end users.
self._crs = "\b" * (self._nticks + 3)
Definition at line 26 of file Spinner.py.
References paramonte.timing.Spinner.Spinner.__init__().
Referenced by paramonte.timing.Spinner.Spinner.__init__().
Member Function Documentation
spin()
def paramonte.timing.Spinner.Spinner.spin (self, fraction)
Rotate the tick mark of the spinner and display the percentage value of the input fraction.
This is a dynamic method of the class pm.timing.Spinner.
Parameters
[in,out] self : The implicitly-passed input argument representing the parent object of the method.
[in] fraction : The input scalar Python fractional real (0 <= fraction <= 1) representing the fraction of work so far accomplished.
Possible calling interfaces ⛓
import paramonte as pm
spinner = pm.timing.Spinner(tickmarks = tickmarks)
spinner.spin(fraction)
Note
See the documentation of the class constructor for example usage.
Final Remarks ⛓
If you believe this algorithm or its documentation can be improved, we appreciate your contribution and help to edit this page's documentation and source file on GitHub.
For details on the naming abbreviations, see this page.
For details on the naming conventions, see this page.
This software is distributed under the MIT license with additional terms outlined below.
If you use any parts or concepts from this library to any extent, please acknowledge the usage by citing the relevant publications of the ParaMonte library.
If you regenerate any parts/ideas from this library in a programming environment other than those currently supported by this ParaMonte library (i.e., other than C, C++, Fortran, MATLAB, Python, R), please also ask the end users to cite this original ParaMonte library.
This software is available to the public under a highly permissive license.
Help us justify its continued development and maintenance by acknowledging its benefit to society, distributing it, and contributing to it.
Copyright
Computational Data Science Lab
Author:
Fatemeh Bagheri, May 20 2024, 1:25 PM, NASA Goddard Space Flight Center (GSFC), Washington, D.C.
Amir Shahmoradi, May 16 2016, 9:03 AM, Oden Institute for Computational Engineering and Sciences (ICES), UT Austin
Definition at line 90 of file Spinner.py.
References paramonte.timing.Spinner.Spinner._clock, paramonte.timing.Spinner.Spinner._nticks, paramonte.timing.Spinner.Spinner.spin(), and paramonte.timing.Spinner.Spinner.tickmarks.
Referenced by paramonte.timing.Spinner.Spinner.spin().
Member Data Documentation
_clock
paramonte.timing.Spinner.Spinner._clock private
The Python string containing a sequence of carriage returns (crs) characters that must appear at the beginning of the spinner.
The scalar integer representing the index of the tickmarks attribute.
Warning
This is an internal hidden class attribute that is inaccessible to the end users.
Definition at line 81 of file Spinner.py.
Referenced by paramonte.timing.Spinner.Spinner.spin().
_nticks
paramonte.timing.Spinner.Spinner._nticks private
The Python integer containing the length of tickmarks.
Warning
This is an internal hidden class attribute that is inaccessible to the end users.
Definition at line 71 of file Spinner.py.
Referenced by paramonte.timing.Spinner.Spinner.spin().
tickmarks
paramonte.timing.Spinner.Spinner.tickmarks
The Python string containing the set of characters that represent the passage of time in the spinner.
Definition at line 64 of file Spinner.py.
Referenced by paramonte.timing.Spinner.Spinner.spin().
The documentation for this class was generated from the following file:
src/python/main/paramonte/timing/Spinner.py