ParaMonte Python 3.0.0: FrozenClass.FrozenClass Class Reference
FrozenClass.FrozenClass Class Reference
This is a Python class for generating object instances whose attributes can be frozen upon request to avoid addition of further attributes to the object.
Public Member Functions
def __setattr__ (self, key, value)
Private Member Functions
def _freeze (self)
Private Attributes
__isfrozen
Static Private Attributes
bool __isfrozen = False
Detailed Description
This is a Python class for generating object instances whose attributes can be frozen upon request to avoid addition of further attributes to the object.
This class does not have a custom constructor.
Returns
fobj : The output scalar Python object of class pm.python.FrozenClass.
Possible calling interfaces ⛓
import paramonte as pm
itis = pm.python.FrozenClass()
Example usage ⛓
Example output ⛓
Final Remarks ⛓
If you believe this algorithm or its documentation can be improved, we appreciate your contribution and help to edit this page's documentation and source file on GitHub.
For details on the naming abbreviations, see this page.
For details on the naming conventions, see this page.
This software is distributed under the MIT license with additional terms outlined below.
If you use any parts or concepts from this library to any extent, please acknowledge the usage by citing the relevant publications of the ParaMonte library.
If you regenerate any parts/ideas from this library in a programming environment other than those currently supported by this ParaMonte library (i.e., other than C, C++, Fortran, MATLAB, Python, R), please also ask the end users to cite this original ParaMonte library.
This software is available to the public under a highly permissive license.
Help us justify its continued development and maintenance by acknowledging its benefit to society, distributing it, and contributing to it.
Copyright
Computational Data Science Lab
Author:
Fatemeh Bagheri, May 20 2024, 1:25 PM, NASA Goddard Space Flight Center (GSFC), Washington, D.C.
Amir Shahmoradi, May 16 2016, 9:03 AM, Oden Institute for Computational Engineering and Sciences (ICES), UT Austin
Definition at line 1 of file FrozenClass.py.
Member Function Documentation
__setattr__()
def FrozenClass.FrozenClass.__setattr__ (self, key, value)
Definition at line 41 of file FrozenClass.py.
References FrozenClass.FrozenClass.__isfrozen, and FrozenClass.FrozenClass.__setattr__().
Referenced by FrozenClass.FrozenClass.__setattr__().
_freeze()
def FrozenClass.FrozenClass._freeze (self) private
Definition at line 49 of file FrozenClass.py.
References FrozenClass.FrozenClass._freeze().
Referenced by FrozenClass.FrozenClass._freeze().
Member Data Documentation
__isfrozen [1/2]
bool FrozenClass.FrozenClass.__isfrozen = False static private
Definition at line 35 of file FrozenClass.py.
Referenced by FrozenClass.FrozenClass.__setattr__().
__isfrozen [2/2]
FrozenClass.FrozenClass.__isfrozen private
Definition at line 50 of file FrozenClass.py.
Referenced by FrozenClass.FrozenClass.__setattr__().
The documentation for this class was generated from the following file:
src/python/main/paramonte/python/FrozenClass.py