ParaMonte Python 3.0.0: paramonte.timing.Timer.Timer Class Reference
paramonte.timing.Timer.Timer Class Reference
This is the base class for generating objects that can time interval consecutively.
Public Member Functions
def __init__ (self)
Return a scalar object of class pm.timing.Timer.
def tic (self)
Reset the timer, equivalent to reconstructing the timer object.
def toc (self)
Return a scalar Python real containing the time past since the (re)construction of the timer object.
def delta (self)
Return a scalar Python real containing the time past since the last time measurement by the timer object (using any of the object methods).
Public Attributes
clock
The scalar Python real containing the most recent timing since the construction of the timer using either pm.timing.Timer.toc() or pm.timing.Timer.delta() methods of the object.
Private Attributes
_start
The scalar Python real containing the timer start.
Detailed Description
This is the base class for generating objects that can time interval consecutively.
The main utility of this timer class is its dynamic delta() method which can compute the time elapsed since the last measurement in one function call.
Note
See the documentation of the class constructor.
See below for information on the attributes (properties).
See below for information on the methods.
Final Remarks ⛓
If you believe this algorithm or its documentation can be improved, we appreciate your contribution and help to edit this page's documentation and source file on GitHub.
For details on the naming abbreviations, see this page.
For details on the naming conventions, see this page.
This software is distributed under the MIT license with additional terms outlined below.
If you use any parts or concepts from this library to any extent, please acknowledge the usage by citing the relevant publications of the ParaMonte library.
If you regenerate any parts/ideas from this library in a programming environment other than those currently supported by this ParaMonte library (i.e., other than C, C++, Fortran, MATLAB, Python, R), please also ask the end users to cite this original ParaMonte library.
This software is available to the public under a highly permissive license.
Help us justify its continued development and maintenance by acknowledging its benefit to society, distributing it, and contributing to it.
Copyright
Computational Data Science Lab
Author:
Joshua Alexander Osborne, May 21 2024, 5:47 AM, University of Texas at Arlington
Fatemeh Bagheri, May 20 2024, 1:25 PM, NASA Goddard Space Flight Center (GSFC), Washington, D.C.
Amir Shahmoradi, May 16 2016, 9:03 AM, Oden Institute for Computational Engineering and Sciences (ICES), UT Austin
Definition at line 1 of file Timer.py.
Constructor & Destructor Documentation
__init__()
def paramonte.timing.Timer.Timer.__init__ (self)
Return a scalar object of class pm.timing.Timer.
This is the constructor of the class pm.timing.Timer.
Returns
self : The output scalar object of class pm.timing.Timer.
Possible calling interfaces ⛓
import paramonte as pm
self = pm.timing.Timer()
Example usage ⛓
#!/usr/bin/env python3
import os
import sys
import numpy as np
from time import sleep
srcdir = os.path.dirname(__file__)
os.chdir(srcdir) # Change working directory to source code directory.
sys.path.append(os.path.join(srcdir, "..", "..", "..")) # import paramonte module locally if available.
import paramonte as pm
print('timer = pm.timing.Timer()')
timer = pm.timing.Timer()
print('sleep(1)')
sleep(1)
print('timer.toc()')
print(timer.toc())
print('sleep(.5)')
sleep(.5)
print('timer.toc()')
print(timer.toc())
print('sleep(.2)')
sleep(.2)
print('timer.delta()')
print(timer.delta())
print('timer.tic() # reset/start timer.')
timer.tic() # reset/start timer.
Example output ⛓
timer = pm.timing.Timer()
sleep(1)
timer.toc()
1.0010831356048584
sleep(.5)
timer.toc()
1.5019521713256836
sleep(.2)
timer.delta()
0.20041108131408691
timer.tic() # reset/start timer.
Final Remarks ⛓
If you believe this algorithm or its documentation can be improved, we appreciate your contribution and help to edit this page's documentation and source file on GitHub.
For details on the naming abbreviations, see this page.
For details on the naming conventions, see this page.
This software is distributed under the MIT license with additional terms outlined below.
If you use any parts or concepts from this library to any extent, please acknowledge the usage by citing the relevant publications of the ParaMonte library.
If you regenerate any parts/ideas from this library in a programming environment other than those currently supported by this ParaMonte library (i.e., other than C, C++, Fortran, MATLAB, Python, R), please also ask the end users to cite this original ParaMonte library.
This software is available to the public under a highly permissive license.
Help us justify its continued development and maintenance by acknowledging its benefit to society, distributing it, and contributing to it.
Copyright
Computational Data Science Lab
Author:
Fatemeh Bagheri, May 20 2024, 1:25 PM, NASA Goddard Space Flight Center (GSFC), Washington, D.C.
Amir Shahmoradi, May 16 2016, 9:03 AM, Oden Institute for Computational Engineering and Sciences (ICES), UT Austin
Definition at line 32 of file Timer.py.
References paramonte.timing.Timer.Timer.__init__().
Referenced by paramonte.timing.Timer.Timer.__init__().
Member Function Documentation
delta()
def paramonte.timing.Timer.Timer.delta (self)
Return a scalar Python real containing the time past since the last time measurement by the timer object (using any of the object methods).
Also, set the clock attribute of the parent object.
This is a dynamic method of the class pm.timing.Timer.
Returns
delta : The output scalar Python real containing the time past since the last time measurement by the timer object.
Possible calling interfaces ⛓
import paramonte as pm
timer = pm.timing.Timer()
delta = timer.delta()
Note
See the documentation of the class constructor for example usage.
Final Remarks ⛓
If you believe this algorithm or its documentation can be improved, we appreciate your contribution and help to edit this page's documentation and source file on GitHub.
For details on the naming abbreviations, see this page.
For details on the naming conventions, see this page.
This software is distributed under the MIT license with additional terms outlined below.
If you use any parts or concepts from this library to any extent, please acknowledge the usage by citing the relevant publications of the ParaMonte library.
If you regenerate any parts/ideas from this library in a programming environment other than those currently supported by this ParaMonte library (i.e., other than C, C++, Fortran, MATLAB, Python, R), please also ask the end users to cite this original ParaMonte library.
This software is available to the public under a highly permissive license.
Help us justify its continued development and maintenance by acknowledging its benefit to society, distributing it, and contributing to it.
Copyright
Computational Data Science Lab
Author:
Fatemeh Bagheri, May 20 2024, 1:25 PM, NASA Goddard Space Flight Center (GSFC), Washington, D.C.
Amir Shahmoradi, May 16 2016, 9:03 AM, Oden Institute for Computational Engineering and Sciences (ICES), UT Austin
Definition at line 152 of file Timer.py.
References paramonte.timing.Timer.Timer.clock, paramonte.timing.Timer.Timer.delta(), and paramonte.timing.Timer.Timer.toc().
Referenced by paramonte.timing.Timer.Timer.delta().
tic()
def paramonte.timing.Timer.Timer.tic (self)
Reset the timer, equivalent to reconstructing the timer object.
This is a dynamic method of the class pm.timing.Timer.
Possible calling interfaces ⛓
import paramonte as pm
timer = pm.timing.Timer()
timer.tic()
Note
See the documentation of the class constructor for example usage.
Final Remarks ⛓
If you believe this algorithm or its documentation can be improved, we appreciate your contribution and help to edit this page's documentation and source file on GitHub.
For details on the naming abbreviations, see this page.
For details on the naming conventions, see this page.
This software is distributed under the MIT license with additional terms outlined below.
If you use any parts or concepts from this library to any extent, please acknowledge the usage by citing the relevant publications of the ParaMonte library.
If you regenerate any parts/ideas from this library in a programming environment other than those currently supported by this ParaMonte library (i.e., other than C, C++, Fortran, MATLAB, Python, R), please also ask the end users to cite this original ParaMonte library.
This software is available to the public under a highly permissive license.
Help us justify its continued development and maintenance by acknowledging its benefit to society, distributing it, and contributing to it.
Copyright
Computational Data Science Lab
Author:
Fatemeh Bagheri, May 20 2024, 1:25 PM, NASA Goddard Space Flight Center (GSFC), Washington, D.C.
Amir Shahmoradi, May 16 2016, 9:03 AM, Oden Institute for Computational Engineering and Sciences (ICES), UT Austin
Definition at line 82 of file Timer.py.
References paramonte.timing.Timer.Timer._start, paramonte.timing.Timer.Timer.clock, and paramonte.timing.Timer.Timer.tic().
Referenced by paramonte.timing.Timer.Timer.tic().
toc()
def paramonte.timing.Timer.Timer.toc (self)
Return a scalar Python real containing the time past since the (re)construction of the timer object.
Also, set the clock attribute of the parent object.
This is a dynamic method of the class pm.timing.Timer.
Returns
clock : The output scalar Python real containing the time past since the (re)construction of the timer object.
Possible calling interfaces ⛓
import paramonte as pm
timer = pm.timing.Timer()
clock = timer.toc()
Note
See the documentation of the class constructor for example usage.
Final Remarks ⛓
If you believe this algorithm or its documentation can be improved, we appreciate your contribution and help to edit this page's documentation and source file on GitHub.
For details on the naming abbreviations, see this page.
For details on the naming conventions, see this page.
This software is distributed under the MIT license with additional terms outlined below.
If you use any parts or concepts from this library to any extent, please acknowledge the usage by citing the relevant publications of the ParaMonte library.
If you regenerate any parts/ideas from this library in a programming environment other than those currently supported by this ParaMonte library (i.e., other than C, C++, Fortran, MATLAB, Python, R), please also ask the end users to cite this original ParaMonte library.
This software is available to the public under a highly permissive license.
Help us justify its continued development and maintenance by acknowledging its benefit to society, distributing it, and contributing to it.
Copyright
Computational Data Science Lab
Author:
Fatemeh Bagheri, May 20 2024, 1:25 PM, NASA Goddard Space Flight Center (GSFC), Washington, D.C.
Amir Shahmoradi, May 16 2016, 9:03 AM, Oden Institute for Computational Engineering and Sciences (ICES), UT Austin
Definition at line 113 of file Timer.py.
References paramonte.timing.Timer.Timer._start, paramonte.timing.Timer.Timer.clock, and paramonte.timing.Timer.Timer.toc().
Referenced by paramonte.timing.Timer.Timer.delta(), and paramonte.timing.Timer.Timer.toc().
Member Data Documentation
_start
paramonte.timing.Timer.Timer._start private
The scalar Python real containing the timer start.
Warning
This is an internal hidden class attribute that is inaccessible to the end users.
Definition at line 69 of file Timer.py.
Referenced by paramonte.timing.Timer.Timer.tic(), and paramonte.timing.Timer.Timer.toc().
clock
paramonte.timing.Timer.Timer.clock
The scalar Python real containing the most recent timing since the construction of the timer using either pm.timing.Timer.toc() or pm.timing.Timer.delta() methods of the object.
Definition at line 76 of file Timer.py.
Referenced by paramonte.timing.Timer.Timer.delta(), paramonte.timing.Timer.Timer.tic(), and paramonte.timing.Timer.Timer.toc().
The documentation for this class was generated from the following file:
src/python/main/paramonte/timing/Timer.py