ParaMonte Fortran 2.0.0: pm_timer Module Reference
pm_timer Module Reference
This module contains the timer procedures and derived types to facilitate timing applications at runtime.
Data Types
interface getTime_proc
This is the abstract interface of the setTime static type-bound procedure component of timer_type abstract type that performs the timing since a user-specified or a processor-dependent origin.
interface setIdle_proc
This is the abstract interface of the wait static type-bound procedure component of timer_type abstract type that keeps the system waiting for the specified amount of seconds.
interface timer_type
This is the abstract base derived type that serves as a simple container template for other timer classes in the ParaMonte library.
interface timerCPU_type
This is the timerCPU_type class, containing attributes and static methods for setting up a timer based on the CPU-clock, using the Fortran intrinsic cpu_time().
interface timerDAT_type
This is the timerDAT_type class, containing attributes and static methods for setting up a timer based on the system-clock, using the Fortran intrinsic date_and_time().
interface timerMPI_type
This is the timerMPI_type class, containing attributes and static methods for setting up a timer based on the MPI intrinsic MPI_Wtime().
interface timerOMP_type
This is the timerMPI_type class, containing attributes and static methods for setting up a timer based on the OpenMP intrinsic omp_get_wtime().
interface timerSYS_type
This is the timerSYS_type class, containing attributes and static methods for setting up a timer based on the system-clock, using the Fortran intrinsic system_clock().
Functions/Subroutines
type(timerMPI_type) type(timerOMP_type) type(timerSYS_type) function timer_typer ()
This is the constructor of the timer_type class.
type(timerCPU_type) function timerCPU_typer ()
This is the constructor of the timerCPU_type class.
type(timerDAT_type) function timerDAT_typer ()
This is the constructor of the timerDAT_type class.
type(timerMPI_type) function timerMPI_typer ()
This is the constructor of the timerMPI_type class.
type(timerOMP_type) function timerOMP_typer ()
This is the constructor of the timerOMP_type class.
type(timerSYS_type) function timerSYS_typer ()
This is the constructor of the timerSYS_type class.
real(RKD) function getTime (since)
Generate and return the time in units of seconds since the specified time since or since an arbitrary processor-dependent time.
real(RKD) function getTimeCPU (since)
Generate and return the CPU time in units of seconds since the specified time since or since an arbitrary processor-dependent time.
real(RKD) function getTimeDAT (since)
Generate and return the calendrical clock time in units of seconds since the specified time since or since the Gregorian calendrical time origin.
real(RKD) function getTimeMPI (since)
Generate and return the MPI clock time in units of seconds since the specified time since or since an arbitrary time origin set by the MPI library.
real(RKD) function getTimeOMP (since)
Generate and return the OpenMP clock time in units of seconds since the specified time since or since an arbitrary time origin set by the OpenMP library.
real(RKD) function getTimeSYS (since)
Generate and return the system clock time in units of seconds since the specified time since or since an arbitrary processor-dependent time origin.
real(RKD) function getResTimer ()
Generate and return the time resolution by the build-time default timer of the ParaMonte library as used in timer_type, in units of seconds.
real(RKD) function getResTimerCPU ()
Generate and return the time resolution of the Fortran intrinsic cpu_time(), used in timerCPU_type, in units of seconds.
pure real(RKD) function getResTimerDAT ()
Generate and return the time resolution of the Fortran intrinsic date_and_time(), used in timerDAT_type, in units of seconds.
real(RKD) function getResTimerMPI ()
Generate and return the time resolution of the MPI intrinsic timer, used in timerMPI_type, in units of seconds.
real(RKD) function getResTimerOMP ()
Generate and return the time resolution of the OpenMP intrinsic timer, used in timerOMP_type, in units of seconds.
real(RKD) function getResTimerSYS ()
Generate and return the time resolution of the Fortran intrinsic system_clock(), used in timerSYS_type, in units of seconds.
subroutine setIdle (seconds)
Set the processor in sleep mode for the input requested number of seconds via the default timer of the ParaMonte library.
subroutine setIdleCPU (seconds)
Set the processor in sleep mode for the input requested number of seconds via the Fortran intrinsic cpu_time().
subroutine setIdleDAT (seconds)
Set the processor in sleep mode for the input requested number of seconds via the Fortran intrinsic date_and_time().
subroutine setIdleMPI (seconds)
Set the processor in sleep mode for the input requested number of seconds via the MPI intrinsic timer MPI_Wtime().
subroutine setIdleOMP (seconds)
Set the processor in sleep mode for the input requested number of seconds via the OpenMP intrinsic timer omp_get_wtime().
subroutine setIdleSYS (seconds)
Set the processor in sleep mode for the input requested number of seconds via the Fortran intrinsic system_clock().
Variables
character(*, SK), parameter MODULE_NAME = "@pm_timer"
Detailed Description
This module contains the timer procedures and derived types to facilitate timing applications at runtime.
Currently, five types of timers are available in this module in addition to a generic timer class.
timer_type
This is a generic timer class which defaults to the most appropriate timer type based on the ParaMonte library build.
If the ParaMonte library is built for serial applications, then timerSYS_type is used.
If the ParaMonte library is built for MPI-parallel applications, then timerMPI_type is used.
If the ParaMonte library is built for OpenMP-parallel applications, then timerOMP_type is used.
Use this timer class if you are not sure which timer is suitable for the task.
timerCPU_type
This timer relies on the Fortran intrinsic cpu_time().
This timer is not ideal for timing parallel or multi-threaded applications because cpu_time() returns the sum of the total time spent by all processes.
The timing precision of the Fortran intrinsic cpu_time() is processor-dependent.
There is currently no direct way of measuring the time resolution of cpu_time().
This module uses a simple cycling method to compute the resolution of the time returned by cpu_time().
It computes the resolution as the least noticeable non-zero time difference between any two time points returned by cpu_time().
On processors with no clock, the time returned by cpu_time() is negative to indicate the lack of a processor clock.
The clock existence is verified only if the library is built with the preprocessor macro CHECK_ENABLED=1.
timerDAT_type
This timer relies on the Fortran intrinsic date_and_time().
This timer is not ideal for high resolution time measurements because the resolution is limited to milliseconds.
timerMPI_type
This timer relies on the MPI library intrinsic mpi_wtime().
The clock time resolution is computed by calling mpi_wtick().
This timer is ideal for high resolution (e.g., nanseconds) time measurements in distributed parallel applications.
This timer is available only when the ParaMonte library is built with MPI support enabled.
This timer requires the MPI library to have been already initialized via mpi_init() and not have been finalized via mpi_finalize().
These conditions are verified only if the library is built with the preprocessor macro CHECK_ENABLED=1.
timerOMP_type
This timer relies on the OpenMP library intrinsic omp_get_wtime().
The clock time resolution is computed by calling omp_get_wtick().
This timer is ideal for high resolution time measurements in multithreaded parallel applications.
This timer is available only when the ParaMonte library is built with OpenMP support enabled.
This timer measures elapsed wall clock time in seconds.
The time is measured per thread.
No guarantee can be made that two distinct threads measure the same time.
Time is measured from some time in the past, which is an arbitrary time guaranteed not to change during the execution of the program.
timerSYS_type
This timer relies on the Fortran intrinsic system_clock().
This timer can be used in most parallel or serial timing scenarios.
The resolution of this timer is processor-dependent.
Time is measured from some time in the past, which is an arbitrary time guaranteed not to change during the execution of the program.
The time is measured per processor.
On processors with no clock, sysctem_clock() returns a negative clock count to indicate the lack of a processor clock.
The clock existence is verified only if the library is built with the preprocessor macro CHECK_ENABLED=1.
Test:
test_pm_timer
Final Remarks ⛓
If you believe this algorithm or its documentation can be improved, we appreciate your contribution and help to edit this page's documentation and source file on GitHub.
For details on the naming abbreviations, see this page.
For details on the naming conventions, see this page.
This software is distributed under the MIT license with additional terms outlined below.
If you use any parts or concepts from this library to any extent, you must acknowledge the usage by citing the relevant publications of the ParaMonte library.
If you regenerate any parts/ideas from this library in a programming environment other than those currently supported by this ParaMonte library (i.e., other than C, C++, Fortran, MATLAB, Python, R), you must also ask the end users to cite this original ParaMonte library.
Copyright
Computational Data Science Lab
Author:
Amir Shahmoradi, March 22, 2012, 2:21 PM, National Institute for Fusion Studies, The University of Texas at Austin
Function/Subroutine Documentation
getResTimer()
real(RKD) function pm_timer::getResTimer
Generate and return the time resolution by the build-time default timer of the ParaMonte library as used in timer_type, in units of seconds.
This function relies on either of the following lower-level module functions depending on the ParaMonte library build:
getResTimerMPI for MPI-enabled parallel builds of the ParaMonte library.
getResTimerOMP for OpenMP-enabled parallel builds of the ParaMonte library.
getResTimerSYS for all other parallel or serial builds of the ParaMonte library.
Returns
resolution : The output scalar of type real of kind double precision RKD, containing the time resolution of the clock in units of seconds.
Possible calling interfaces ⛓
use pm_timer, only: getResTimer
real(RKD) :: resolution
resolution = getResTimer()
Remarks
The procedures under discussion are impure.
See also
timer_type
Example usage ⛓
program example
    use pm_kind, only: SK, IK, LK, RKD
    use pm_io, only: display_type
    use pm_timer, only: getResTimer
    implicit none
    type(display_type)  :: disp
    disp = display_type(file = "main.out.F90")
    call disp%skip()
    call disp%show("getResTimer()")
    call disp%show( getResTimer() )
    call disp%skip()
end program example
Example Unix compile command via Intel ifort compiler ⛓
#!/usr/bin/env sh
rm main.exe
ifort -fpp -standard-semantics -O3 -Wl,-rpath,../../../lib -I../../../inc main.F90 ../../../lib/libparamonte_fortran_*_intel* -o main.exe
./main.exe
Example Windows Batch compile command via Intel ifort compiler ⛓
del main.exe
set PATH=..\..\..\lib;%PATH%
ifort /fpp /standard-semantics /O3 /I:..\..\..\include main.F90 ..\..\..\lib\libparamonte_fortran_*_intel*.lib /exe:main.exe
main.exe
Example Unix / MinGW compile command via GNU gfortran compiler ⛓
#!/usr/bin/env sh
rm main.exe
gfortran -cpp -ffree-line-length-none -O3 -Wl,-rpath,../../../lib -I../../../inc main.F90 ../../../lib/libparamonte_fortran_*_gnu* -o main.exe
./main.exe
Example output ⛓
getResTimer()
+0.10000000000000001E-8
Test:
test_pm_timer
Final Remarks ⛓
If you believe this algorithm or its documentation can be improved, we appreciate your contribution and help to edit this page's documentation and source file on GitHub.
For details on the naming abbreviations, see this page.
For details on the naming conventions, see this page.
This software is distributed under the MIT license with additional terms outlined below.
If you use any parts or concepts from this library to any extent, you must acknowledge the usage by citing the relevant publications of the ParaMonte library.
If you regenerate any parts/ideas from this library in a programming environment other than those currently supported by this ParaMonte library (i.e., other than C, C++, Fortran, MATLAB, Python, R), you must also ask the end users to cite this original ParaMonte library.
Copyright
Computational Data Science Lab
Author:
Amir Shahmoradi, March 22, 2012, 00:00 AM, National Institute for Fusion Studies, The University of Texas at Austin
Definition at line 1260 of file pm_timer.F90.
References getResTimerMPI(), getResTimerOMP(), and getResTimerSYS().
getResTimerCPU()
real(RKD) function pm_timer::getResTimerCPU
Generate and return the time resolution of the Fortran intrinsic cpu_time(), used in timerCPU_type, in units of seconds.
See also the documentation details of pm_timer.
Returns
resolution : The output scalar of type real of kind double precision RKD, containing the time resolution of the CPU clock in units of seconds.
Possible calling interfaces ⛓
use pm_timer, only: getResTimerCPU
real(RKD) :: resolution
resolution = getResTimerCPU()
Remarks
The procedures under discussion are impure.
See also
getResTimerSYS
Example usage ⛓
program example
    use pm_kind, only: SK, IK, LK, RKD
    use pm_io, only: display_type
    use pm_timer, only: getResTimerCPU
    implicit none
    type(display_type)  :: disp
    disp = display_type(file = "main.out.F90")
    call disp%skip()
    call disp%show("getResTimerCPU()")
    call disp%show( getResTimerCPU() )
    call disp%skip()
end program example
Example Unix compile command via Intel ifort compiler ⛓
#!/usr/bin/env sh
rm main.exe
ifort -fpp -standard-semantics -O3 -Wl,-rpath,../../../lib -I../../../inc main.F90 ../../../lib/libparamonte_fortran_*_intel* -o main.exe
./main.exe
Example Windows Batch compile command via Intel ifort compiler ⛓
del main.exe
set PATH=..\..\..\lib;%PATH%
ifort /fpp /standard-semantics /O3 /I:..\..\..\include main.F90 ..\..\..\lib\libparamonte_fortran_*_intel*.lib /exe:main.exe
main.exe
Example Unix / MinGW compile command via GNU gfortran compiler ⛓
#!/usr/bin/env sh
rm main.exe
gfortran -cpp -ffree-line-length-none -O3 -Wl,-rpath,../../../lib -I../../../inc main.F90 ../../../lib/libparamonte_fortran_*_gnu* -o main.exe
./main.exe
Example output ⛓
getResTimerCPU()
+0.10000000000001327E-5
Test:
test_pm_timer
Final Remarks ⛓
If you believe this algorithm or its documentation can be improved, we appreciate your contribution and help to edit this page's documentation and source file on GitHub.
For details on the naming abbreviations, see this page.
For details on the naming conventions, see this page.
This software is distributed under the MIT license with additional terms outlined below.
If you use any parts or concepts from this library to any extent, you must acknowledge the usage by citing the relevant publications of the ParaMonte library.
If you regenerate any parts/ideas from this library in a programming environment other than those currently supported by this ParaMonte library (i.e., other than C, C++, Fortran, MATLAB, Python, R), you must also ask the end users to cite this original ParaMonte library.
Copyright
Computational Data Science Lab
Author:
Amir Shahmoradi, March 22, 2012, 00:00 AM, National Institute for Fusion Studies, The University of Texas at Austin
Definition at line 1315 of file pm_timer.F90.
Referenced by pm_timer::timerCPU_type::timerCPU_typer().
getResTimerDAT()
pure real(RKD) function pm_timer::getResTimerDAT
Generate and return the time resolution of the Fortran intrinsic date_and_time(), used in timerDAT_type, in units of seconds.
See also the documentation details of pm_timer.
Returns
resolution : The output scalar of type real of kind double precision RKD, containing the time resolution of date_and_time() in units of seconds.
Possible calling interfaces ⛓
use pm_timer, only: getResTimerDAT
real(RKD) :: resolution
resolution = getResTimerDAT()
Remarks
The procedures under discussion are pure.
See also
getResTimerSYS
Example usage ⛓
program example
    use pm_kind, only: SK, IK, LK, RKD
    use pm_io, only: display_type
    use pm_timer, only: getResTimerDAT
    implicit none
    type(display_type)  :: disp
    disp = display_type(file = "main.out.F90")
    call disp%skip()
    call disp%show("getResTimerDAT()")
    call disp%show( getResTimerDAT() )
    call disp%skip()
end program example
Example Unix compile command via Intel ifort compiler ⛓
#!/usr/bin/env sh
rm main.exe
ifort -fpp -standard-semantics -O3 -Wl,-rpath,../../../lib -I../../../inc main.F90 ../../../lib/libparamonte_fortran_*_intel* -o main.exe
./main.exe
Example Windows Batch compile command via Intel ifort compiler ⛓
del main.exe
set PATH=..\..\..\lib;%PATH%
ifort /fpp /standard-semantics /O3 /I:..\..\..\include main.F90 ..\..\..\lib\libparamonte_fortran_*_intel*.lib /exe:main.exe
main.exe
Example Unix / MinGW compile command via GNU gfortran compiler ⛓
#!/usr/bin/env sh
rm main.exe
gfortran -cpp -ffree-line-length-none -O3 -Wl,-rpath,../../../lib -I../../../inc main.F90 ../../../lib/libparamonte_fortran_*_gnu* -o main.exe
./main.exe
Example output ⛓
getResTimerDAT()
+0.10000000000000000E-2
Test:
test_pm_timer
Final Remarks ⛓
If you believe this algorithm or its documentation can be improved, we appreciate your contribution and help to edit this page's documentation and source file on GitHub.
For details on the naming abbreviations, see this page.
For details on the naming conventions, see this page.
This software is distributed under the MIT license with additional terms outlined below.
If you use any parts or concepts from this library to any extent, you must acknowledge the usage by citing the relevant publications of the ParaMonte library.
If you regenerate any parts/ideas from this library in a programming environment other than those currently supported by this ParaMonte library (i.e., other than C, C++, Fortran, MATLAB, Python, R), you must also ask the end users to cite this original ParaMonte library.
Copyright
Computational Data Science Lab
Author:
Amir Shahmoradi, March 22, 2012, 00:00 AM, National Institute for Fusion Studies, The University of Texas at Austin
Definition at line 1372 of file pm_timer.F90.
getResTimerMPI()
real(RKD) function pm_timer::getResTimerMPI
Generate and return the time resolution of the MPI intrinsic timer, used in timerMPI_type, in units of seconds.
See also the documentation details of pm_timer.
Returns
resolution : The output scalar of type real of kind double precision RKD, containing the time resolution of mpi_wtime() in units of seconds.
Possible calling interfaces ⛓
use pm_timer, only: getResTimerMPI
real(RKD) :: resolution
resolution = getResTimerMPI()
Warning
This procedure exists only if the library is built with the preprocessor macro MPI_ENABLED=1.
See also
getResTimerSYS
Example usage ⛓
program example
    use pm_kind, only: SK, IK, LK, RKD
    use pm_io, only: display_type
    implicit none
    type(display_type) :: disp
    disp = display_type(file = "main.out.F90")
#if defined MPI_VERSION
    block
        use pm_timer, only: getResTimerMPI
        call disp%skip()
        call disp%show("getResTimerMPI()")
        call disp%show( getResTimerMPI() )
        call disp%skip()
    end block
#else
    call disp%show("The MPI timer is unavailable, because this example has not been linked with an MPI library.")
#endif
end program example
Example Unix compile command via Intel ifort compiler ⛓
#!/usr/bin/env sh
rm main.exe
ifort -fpp -standard-semantics -O3 -Wl,-rpath,../../../lib -I../../../inc main.F90 ../../../lib/libparamonte_fortran_*_intel* -o main.exe
./main.exe
Example Windows Batch compile command via Intel ifort compiler ⛓
del main.exe
set PATH=..\..\..\lib;%PATH%
ifort /fpp /standard-semantics /O3 /I:..\..\..\include main.F90 ..\..\..\lib\libparamonte_fortran_*_intel*.lib /exe:main.exe
main.exe
Example Unix / MinGW compile command via GNU gfortran compiler ⛓
#!/usr/bin/env sh
rm main.exe
gfortran -cpp -ffree-line-length-none -O3 -Wl,-rpath,../../../lib -I../../../inc main.F90 ../../../lib/libparamonte_fortran_*_gnu* -o main.exe
./main.exe
Example output ⛓
The MPI timer is unavailable, because this example has not been linked with an MPI library.
Test:
test_pm_timer
Final Remarks ⛓
If you believe this algorithm or its documentation can be improved, we appreciate your contribution and help to edit this page's documentation and source file on GitHub.
For details on the naming abbreviations, see this page.
For details on the naming conventions, see this page.
This software is distributed under the MIT license with additional terms outlined below.
If you use any parts or concepts from this library to any extent, you must acknowledge the usage by citing the relevant publications of the ParaMonte library.
If you regenerate any parts/ideas from this library in a programming environment other than those currently supported by this ParaMonte library (i.e., other than C, C++, Fortran, MATLAB, Python, R), you must also ask the end users to cite this original ParaMonte library.
Copyright
Computational Data Science Lab
Author:
Amir Shahmoradi, March 22, 2012, 00:00 AM, National Institute for Fusion Studies, The University of Texas at Austin
Definition at line 1423 of file pm_timer.F90.
Referenced by getResTimer().
getResTimerOMP()
real(RKD) function pm_timer::getResTimerOMP
Generate and return the time resolution of the OpenMP intrinsic timer, used in timerOMP_type, in units of seconds.
See also the documentation details of pm_timer.
Returns
resolution : The output scalar of type real of kind double precision RKD, containing the time resolution of mpi_wtime() in units of seconds.
Possible calling interfaces ⛓
use pm_timer, only: getResTimerOMP
real(RKD) :: resolution
resolution = getResTimerOMP()
Warning
This procedure exists only if the library is built with the preprocessor macro OMP_ENABLED=1.
See also
getResTimerSYS
Example usage ⛓
program example
    use pm_kind, only: SK, IK, LK, RKD
    use pm_io, only: display_type
    implicit none
    type(display_type)  :: disp
    disp = display_type(file = "main.out.F90")
#if defined _OPENMP
    block
        use pm_timer, only: getResTimerOMP
        call disp%skip()
        call disp%show("getResTimerOMP()")
        call disp%show( getResTimerOMP() )
        call disp%skip()
    end block
#else
    call disp%show("The OMP timer is unavailable, because this example has not been linked with an OpenMP library.")
#endif
end program example
Example Unix compile command via Intel ifort compiler ⛓
#!/usr/bin/env sh
rm main.exe
ifort -fpp -standard-semantics -O3 -Wl,-rpath,../../../lib -I../../../inc main.F90 ../../../lib/libparamonte_fortran_*_intel* -o main.exe
./main.exe
Example Windows Batch compile command via Intel ifort compiler ⛓
del main.exe
set PATH=..\..\..\lib;%PATH%
ifort /fpp /standard-semantics /O3 /I:..\..\..\include main.F90 ..\..\..\lib\libparamonte_fortran_*_intel*.lib /exe:main.exe
main.exe
Example Unix / MinGW compile command via GNU gfortran compiler ⛓
#!/usr/bin/env sh
rm main.exe
gfortran -cpp -ffree-line-length-none -O3 -Wl,-rpath,../../../lib -I../../../inc main.F90 ../../../lib/libparamonte_fortran_*_gnu* -o main.exe
./main.exe
Example output ⛓
The OMP timer is unavailable, because this example has not been linked with an OpenMP library.
Test:
test_pm_timer
Final Remarks ⛓
If you believe this algorithm or its documentation can be improved, we appreciate your contribution and help to edit this page's documentation and source file on GitHub.
For details on the naming abbreviations, see this page.
For details on the naming conventions, see this page.
This software is distributed under the MIT license with additional terms outlined below.
If you use any parts or concepts from this library to any extent, you must acknowledge the usage by citing the relevant publications of the ParaMonte library.
If you regenerate any parts/ideas from this library in a programming environment other than those currently supported by this ParaMonte library (i.e., other than C, C++, Fortran, MATLAB, Python, R), you must also ask the end users to cite this original ParaMonte library.
Copyright
Computational Data Science Lab
Author:
Amir Shahmoradi, March 22, 2012, 00:00 AM, National Institute for Fusion Studies, The University of Texas at Austin
Definition at line 1476 of file pm_timer.F90.
Referenced by getResTimer().
getResTimerSYS()
real(RKD) function pm_timer::getResTimerSYS
Generate and return the time resolution of the Fortran intrinsic system_clock(), used in timerSYS_type, in units of seconds.
See also the documentation details of pm_timer.
Returns
resolution : The output scalar of type real of kind double precision RKD, containing the time resolution of the system clock in units of seconds.
Possible calling interfaces ⛓
use pm_timer, only: getResTimerSYS
real(RKD) :: resolution
resolution = getResTimerSYS()
Remarks
The procedures under discussion are impure.
See also
timerSYS_type
Example usage ⛓
program example
    use pm_kind, only: SK, IK, LK, RKD
    use pm_io, only: display_type
    use pm_timer, only: getResTimerSYS
    implicit none
    type(display_type)  :: disp
    disp = display_type(file = "main.out.F90")
    call disp%skip()
    call disp%show("getResTimerSYS()")
    call disp%show( getResTimerSYS() )
    call disp%skip()
end program example
Example Unix compile command via Intel ifort compiler ⛓
#!/usr/bin/env sh
rm main.exe
ifort -fpp -standard-semantics -O3 -Wl,-rpath,../../../lib -I../../../inc main.F90 ../../../lib/libparamonte_fortran_*_intel* -o main.exe
./main.exe
Example Windows Batch compile command via Intel ifort compiler ⛓
del main.exe
set PATH=..\..\..\lib;%PATH%
ifort /fpp /standard-semantics /O3 /I:..\..\..\include main.F90 ..\..\..\lib\libparamonte_fortran_*_intel*.lib /exe:main.exe
main.exe
Example Unix / MinGW compile command via GNU gfortran compiler ⛓
#!/usr/bin/env sh
rm main.exe
gfortran -cpp -ffree-line-length-none -O3 -Wl,-rpath,../../../lib -I../../../inc main.F90 ../../../lib/libparamonte_fortran_*_gnu* -o main.exe
./main.exe
Example output ⛓
getResTimerSYS()
+0.10000000000000001E-8
Test:
test_pm_timer
Final Remarks ⛓
If you believe this algorithm or its documentation can be improved, we appreciate your contribution and help to edit this page's documentation and source file on GitHub.
For details on the naming abbreviations, see this page.
For details on the naming conventions, see this page.
This software is distributed under the MIT license with additional terms outlined below.
If you use any parts or concepts from this library to any extent, you must acknowledge the usage by citing the relevant publications of the ParaMonte library.
If you regenerate any parts/ideas from this library in a programming environment other than those currently supported by this ParaMonte library (i.e., other than C, C++, Fortran, MATLAB, Python, R), you must also ask the end users to cite this original ParaMonte library.
Copyright
Computational Data Science Lab
Author:
Amir Shahmoradi, March 22, 2012, 00:00 AM, National Institute for Fusion Studies, The University of Texas at Austin
Definition at line 1527 of file pm_timer.F90.
Referenced by getResTimer(), and pm_timer::timerSYS_type::timerSYS_typer().
getTime()
real(RKD) function pm_timer::getTime (real(RKD), intent(in), optional since)
Generate and return the time in units of seconds since the specified time since or since an arbitrary processor-dependent time.
This function relies on either of the following lower-level module functions depending on the ParaMonte library build:
getTimeMPI for MPI-enabled parallel builds of the ParaMonte library.
getTimeOMP for OpenMP-enabled parallel builds of the ParaMonte library.
getTimeSYS for all other parallel or serial builds of the ParaMonte library.
Parameters
[in] since : The input scalar of type real of kind double precision RKD representing the time origin (epoch) in seconds.
(optional. If not present, its value is processor-dependent but constant at runtime.)
Returns
timeInSec : The output scalar of type real of kind double precision RKD, containing the time in seconds since a specified time since or since an arbitrary processor-dependent time.
Possible calling interfaces ⛓
use pm_timer, only: getTime
real(RKD) :: timeInSec
logical(LK) :: failed
timeInSec = getTime(since = since)
Remarks
The procedures under discussion are impure.
See also
timer_type
Example usage ⛓
program example
    use pm_kind, only: SK, IK, LK, RKD
    use pm_io, only: display_type
    use pm_timer, only: getTime
    use pm_timer, only: setIdle
    implicit none
    real(RKD)           :: since
    type(display_type)  :: disp
    disp = display_type(file = "main.out.F90")
    call disp%skip()
    call disp%show("since = getTime()")
                    since = getTime()
    call disp%show("call setIdle(seconds = 0.1_RKD)")
                    call setIdle(seconds = 0.1_RKD)
    call disp%show("getTime(since)")
    call disp%show( getTime(since) )
    call disp%skip()
end program example
Example Unix compile command via Intel ifort compiler ⛓
#!/usr/bin/env sh
rm main.exe
ifort -fpp -standard-semantics -O3 -Wl,-rpath,../../../lib -I../../../inc main.F90 ../../../lib/libparamonte_fortran_*_intel* -o main.exe
./main.exe
Example Windows Batch compile command via Intel ifort compiler ⛓
del main.exe
set PATH=..\..\..\lib;%PATH%
ifort /fpp /standard-semantics /O3 /I:..\..\..\include main.F90 ..\..\..\lib\libparamonte_fortran_*_intel*.lib /exe:main.exe
main.exe
Example Unix / MinGW compile command via GNU gfortran compiler ⛓
#!/usr/bin/env sh
rm main.exe
gfortran -cpp -ffree-line-length-none -O3 -Wl,-rpath,../../../lib -I../../../inc main.F90 ../../../lib/libparamonte_fortran_*_gnu* -o main.exe
./main.exe
Example output ⛓
since = getTime()
call setIdle(seconds = 0.1_RKD)
getTime(since)
+0.10001578798983246
Test:
test_pm_timer
Final Remarks ⛓
If you believe this algorithm or its documentation can be improved, we appreciate your contribution and help to edit this page's documentation and source file on GitHub.
For details on the naming abbreviations, see this page.
For details on the naming conventions, see this page.
This software is distributed under the MIT license with additional terms outlined below.
If you use any parts or concepts from this library to any extent, you must acknowledge the usage by citing the relevant publications of the ParaMonte library.
If you regenerate any parts/ideas from this library in a programming environment other than those currently supported by this ParaMonte library (i.e., other than C, C++, Fortran, MATLAB, Python, R), you must also ask the end users to cite this original ParaMonte library.
Copyright
Computational Data Science Lab
Author:
Amir Shahmoradi, March 22, 2012, 00:00 AM, National Institute for Fusion Studies, The University of Texas at Austin
Definition at line 857 of file pm_timer.F90.
References getTimeMPI(), getTimeOMP(), and getTimeSYS().
getTimeCPU()
real(RKD) function pm_timer::getTimeCPU (real(RKD), intent(in), optional since)
Generate and return the CPU time in units of seconds since the specified time since or since an arbitrary processor-dependent time.
See also the documentation details of pm_timer.
Parameters
[in] since : The input scalar of type real of kind double precision RKD representing the time origin (epoch) in seconds.
(optional. If not present, its value is processor-dependent but constant at runtime.)
Returns
timeInSec : The output scalar of type real of kind double precision RKD, containing the time in seconds since a specified time since or since an arbitrary processor-dependent time.
Possible calling interfaces ⛓
use pm_timer, only: getTimeCPU
real(RKD) :: timeInSec
logical(LK) :: failed
timeInSec = getTimeCPU(since = since)
Remarks
The procedures under discussion are impure.
See also
timerCPU_type
Example usage ⛓
program example
    use pm_kind, only: SK, IK, LK, RKD
    use pm_io, only: display_type
    use pm_timer, only: getTimeCPU
    use pm_timer, only: setIdleCPU
    implicit none
    real(RKD)           :: since
    type(display_type)  :: disp
    disp = display_type(file = "main.out.F90")
    call disp%skip()
    call disp%show("since = getTimeCPU()")
                    since = getTimeCPU()
    call disp%show("call setIdleCPU(seconds = 0.1_RKD)")
                    call setIdleCPU(seconds = 0.1_RKD)
    call disp%show("getTimeCPU(since)")
    call disp%show( getTimeCPU(since) )
    call disp%skip()
end program example
Example Unix compile command via Intel ifort compiler ⛓
#!/usr/bin/env sh
rm main.exe
ifort -fpp -standard-semantics -O3 -Wl,-rpath,../../../lib -I../../../inc main.F90 ../../../lib/libparamonte_fortran_*_intel* -o main.exe
./main.exe
Example Windows Batch compile command via Intel ifort compiler ⛓
del main.exe
set PATH=..\..\..\lib;%PATH%
ifort /fpp /standard-semantics /O3 /I:..\..\..\include main.F90 ..\..\..\lib\libparamonte_fortran_*_intel*.lib /exe:main.exe
main.exe
Example Unix / MinGW compile command via GNU gfortran compiler ⛓
#!/usr/bin/env sh
rm main.exe
gfortran -cpp -ffree-line-length-none -O3 -Wl,-rpath,../../../lib -I../../../inc main.F90 ../../../lib/libparamonte_fortran_*_gnu* -o main.exe
./main.exe
Example output ⛓
since = getTimeCPU()
call setIdleCPU(seconds = 0.1_RKD)
getTimeCPU(since)
+0.10005200000000000
Test:
test_pm_timer
Final Remarks ⛓
If you believe this algorithm or its documentation can be improved, we appreciate your contribution and help to edit this page's documentation and source file on GitHub.
For details on the naming abbreviations, see this page.
For details on the naming conventions, see this page.
This software is distributed under the MIT license with additional terms outlined below.
If you use any parts or concepts from this library to any extent, you must acknowledge the usage by citing the relevant publications of the ParaMonte library.
If you regenerate any parts/ideas from this library in a programming environment other than those currently supported by this ParaMonte library (i.e., other than C, C++, Fortran, MATLAB, Python, R), you must also ask the end users to cite this original ParaMonte library.
Copyright
Computational Data Science Lab
Author:
Amir Shahmoradi, March 22, 2012, 00:00 AM, National Institute for Fusion Studies, The University of Texas at Austin
Definition at line 917 of file pm_timer.F90.
Referenced by setIdleCPU().
getTimeDAT()
real(RKD) function pm_timer::getTimeDAT (real(RKD), intent(in), optional since)
Generate and return the calendrical clock time in units of seconds since the specified time since or since the Gregorian calendrical time origin.
See also the documentation details of pm_timer.
Parameters
[in] since : The input scalar of type real of kind double precision RKD representing the time origin (epoch) in seconds.
(optional. If not present, its value is the Gregorian calendrical time origin.)
Returns
timeInSec : The output scalar of type real of kind double precision RKD, containing the time in seconds since the specified time origin.
Possible calling interfaces ⛓
use pm_timer, only: getTimeDAT
real(RKD) :: timeInSec
timeInSec = getTimeDAT(since = since)
Remarks
The procedures under discussion are impure.
See also
timerDAT_type
Example usage ⛓
program example
    use pm_kind, only: SK, IK, LK, RKD
    use pm_io, only: display_type
    use pm_timer, only: getTimeDAT
    use pm_timer, only: setIdleDAT
    implicit none
    real(RKD)           :: since
    type(display_type)  :: disp
    disp = display_type(file = "main.out.F90")
    call disp%skip()
    call disp%show("since = getTimeDAT()")
                    since = getTimeDAT()
    call disp%show("call setIdleDAT(seconds = 0.1_RKD)")
                    call setIdleDAT(seconds = 0.1_RKD)
    call disp%show("getTimeDAT(since)")
    call disp%show( getTimeDAT(since) )
    call disp%skip()
end program example
Example Unix compile command via Intel ifort compiler ⛓
#!/usr/bin/env sh
rm main.exe
ifort -fpp -standard-semantics -O3 -Wl,-rpath,../../../lib -I../../../inc main.F90 ../../../lib/libparamonte_fortran_*_intel* -o main.exe
./main.exe
Example Windows Batch compile command via Intel ifort compiler ⛓
del main.exe
set PATH=..\..\..\lib;%PATH%
ifort /fpp /standard-semantics /O3 /I:..\..\..\include main.F90 ..\..\..\lib\libparamonte_fortran_*_intel*.lib /exe:main.exe
main.exe
Example Unix / MinGW compile command via GNU gfortran compiler ⛓
#!/usr/bin/env sh
rm main.exe
gfortran -cpp -ffree-line-length-none -O3 -Wl,-rpath,../../../lib -I../../../inc main.F90 ../../../lib/libparamonte_fortran_*_gnu* -o main.exe
./main.exe
Example output ⛓
since = getTimeDAT()
call setIdleDAT(seconds = 0.1_RKD)
getTimeDAT(since)
+0.10098266601562500
Test:
test_pm_timer
Final Remarks ⛓
If you believe this algorithm or its documentation can be improved, we appreciate your contribution and help to edit this page's documentation and source file on GitHub.
For details on the naming abbreviations, see this page.
For details on the naming conventions, see this page.
This software is distributed under the MIT license with additional terms outlined below.
If you use any parts or concepts from this library to any extent, you must acknowledge the usage by citing the relevant publications of the ParaMonte library.
If you regenerate any parts/ideas from this library in a programming environment other than those currently supported by this ParaMonte library (i.e., other than C, C++, Fortran, MATLAB, Python, R), you must also ask the end users to cite this original ParaMonte library.
Copyright
Computational Data Science Lab
Author:
Amir Shahmoradi, March 22, 2012, 00:00 AM, National Institute for Fusion Studies, The University of Texas at Austin
Definition at line 972 of file pm_timer.F90.
References pm_kind::IK, pm_kind::RKD, and pm_dateTime::SECONDS_PER_DAY.
Referenced by setIdleDAT().
getTimeMPI()
real(RKD) function pm_timer::getTimeMPI (real(RKD), intent(in), optional since)
Generate and return the MPI clock time in units of seconds since the specified time since or since an arbitrary time origin set by the MPI library.
See also the documentation details of pm_timer.
Parameters
[in] since : The input scalar of type real of kind double precision RKD representing the time origin (epoch) in seconds.
(optional. If not present, its value is an arbitrary time origin set by the MPI library.)
Returns
timeInSec : The output scalar of type real of kind double precision RKD, containing the time in seconds since the specified time origin.
Possible calling interfaces ⛓
use pm_timer, only: getTimeMPI
real(RKD) :: timeInSec
timeInSec = getTimeMPI(since = since)
Warning
This procedure exists only if the library is built with the preprocessor macro MPI_ENABLED=1.
Remarks
The procedures under discussion are impure.
See also
timerMPI_type
Example usage ⛓
program example
    use pm_kind, only: SK, IK, LK, RKD
    use pm_io, only: display_type
    implicit none
    real(RKD)           :: since
    type(display_type)  :: disp
    disp = display_type(file = "main.out.F90")
#if defined MPI_VERSION
    block
        use pm_timer, only: getTimeMPI
        use pm_timer, only: setIdleMPI
        call disp%skip()
        call disp%show("since = getTimeMPI()")
                        since = getTimeMPI()
        call disp%show("call setIdleMPI(seconds = 0.1_RKD)")
                        call setIdleMPI(seconds = 0.1_RKD)
        call disp%show("getTimeMPI(since)")
        call disp%show( getTimeMPI(since) )
        call disp%skip()
    end block
#else
    call disp%show("The MPI timer is unavailable, because this example has not been linked with an MPI library.")
#endif
end program example
Example Unix compile command via Intel ifort compiler ⛓
#!/usr/bin/env sh
rm main.exe
ifort -fpp -standard-semantics -O3 -Wl,-rpath,../../../lib -I../../../inc main.F90 ../../../lib/libparamonte_fortran_*_intel* -o main.exe
./main.exe
Example Windows Batch compile command via Intel ifort compiler ⛓
del main.exe
set PATH=..\..\..\lib;%PATH%
ifort /fpp /standard-semantics /O3 /I:..\..\..\include main.F90 ..\..\..\lib\libparamonte_fortran_*_intel*.lib /exe:main.exe
main.exe
Example Unix / MinGW compile command via GNU gfortran compiler ⛓
#!/usr/bin/env sh
rm main.exe
gfortran -cpp -ffree-line-length-none -O3 -Wl,-rpath,../../../lib -I../../../inc main.F90 ../../../lib/libparamonte_fortran_*_gnu* -o main.exe
./main.exe
Example output ⛓
The MPI timer is unavailable, because this example has not been linked with an MPI library.
Test:
test_pm_timer
Final Remarks ⛓
If you believe this algorithm or its documentation can be improved, we appreciate your contribution and help to edit this page's documentation and source file on GitHub.
For details on the naming abbreviations, see this page.
For details on the naming conventions, see this page.
This software is distributed under the MIT license with additional terms outlined below.
If you use any parts or concepts from this library to any extent, you must acknowledge the usage by citing the relevant publications of the ParaMonte library.
If you regenerate any parts/ideas from this library in a programming environment other than those currently supported by this ParaMonte library (i.e., other than C, C++, Fortran, MATLAB, Python, R), you must also ask the end users to cite this original ParaMonte library.
Copyright
Computational Data Science Lab
Author:
Amir Shahmoradi, March 22, 2012, 00:00 AM, National Institute for Fusion Studies, The University of Texas at Austin
Definition at line 1035 of file pm_timer.F90.
References pm_kind::IK, and pm_kind::RKD.
Referenced by getTime(), and setIdleMPI().
getTimeOMP()
real(RKD) function pm_timer::getTimeOMP (real(RKD), intent(in), optional since)
Generate and return the OpenMP clock time in units of seconds since the specified time since or since an arbitrary time origin set by the OpenMP library.
See also the documentation details of pm_timer.
Parameters
[in] since : The input scalar of type real of kind double precision RKD representing the time origin (epoch) in seconds.
(optional. If not present, its value is an arbitrary time origin set by the OpenMP library.)
Returns
timeInSec : The output scalar of type real of kind double precision RKD, containing the time in seconds since the specified time origin.
Possible calling interfaces ⛓
use pm_timer, only: getTimeOMP
real(RKD) :: timeInSec
timeInSec = getTimeOMP(since = since)
Warning
This procedure exists only if the library is built with the preprocessor macro OMP_ENABLED=1.
Remarks
The procedures under discussion are impure.
See also
timerOMP_type
Example usage ⛓
program example
    use pm_kind, only: SK, IK, LK, RKD
    use pm_io, only: display_type
    implicit none
    real(RKD)           :: since
    type(display_type)  :: disp
    disp = display_type(file = "main.out.F90")
#if defined _OPENMP
    block
        use pm_timer, only: getTimeOMP
        use pm_timer, only: setIdleOMP
        call disp%skip()
        call disp%show("since = getTimeOMP()")
                        since = getTimeOMP()
        call disp%show("call setIdleOMP(seconds = 0.1_RKD)")
                        call setIdleOMP(seconds = 0.1_RKD)
        call disp%show("getTimeOMP(since)")
        call disp%show( getTimeOMP(since) )
        call disp%skip()
    end block
#else
    call disp%show("The OMP timer is unavailable, because this example has not been linked with an OpenMP library.")
#endif
end program example
Example Unix compile command via Intel ifort compiler ⛓
#!/usr/bin/env sh
rm main.exe
ifort -fpp -standard-semantics -O3 -Wl,-rpath,../../../lib -I../../../inc main.F90 ../../../lib/libparamonte_fortran_*_intel* -o main.exe
./main.exe
Example Windows Batch compile command via Intel ifort compiler ⛓
del main.exe
set PATH=..\..\..\lib;%PATH%
ifort /fpp /standard-semantics /O3 /I:..\..\..\include main.F90 ..\..\..\lib\libparamonte_fortran_*_intel*.lib /exe:main.exe
main.exe
Example Unix / MinGW compile command via GNU gfortran compiler ⛓
#!/usr/bin/env sh
rm main.exe
gfortran -cpp -ffree-line-length-none -O3 -Wl,-rpath,../../../lib -I../../../inc main.F90 ../../../lib/libparamonte_fortran_*_gnu* -o main.exe
./main.exe
Example output ⛓
The OMP timer is unavailable, because this example has not been linked with an OpenMP library.
Test:
test_pm_timer
Final Remarks ⛓
If you believe this algorithm or its documentation can be improved, we appreciate your contribution and help to edit this page's documentation and source file on GitHub.
For details on the naming abbreviations, see this page.
For details on the naming conventions, see this page.
This software is distributed under the MIT license with additional terms outlined below.
If you use any parts or concepts from this library to any extent, you must acknowledge the usage by citing the relevant publications of the ParaMonte library.
If you regenerate any parts/ideas from this library in a programming environment other than those currently supported by this ParaMonte library (i.e., other than C, C++, Fortran, MATLAB, Python, R), you must also ask the end users to cite this original ParaMonte library.
Copyright
Computational Data Science Lab
Author:
Amir Shahmoradi, March 22, 2012, 00:00 AM, National Institute for Fusion Studies, The University of Texas at Austin
Definition at line 1096 of file pm_timer.F90.
References pm_kind::IK, and pm_kind::RKD.
Referenced by getTime(), and setIdleOMP().
getTimeSYS()
real(RKD) function pm_timer::getTimeSYS (real(RKD), intent(in), optional since)
Generate and return the system clock time in units of seconds since the specified time since or since an arbitrary processor-dependent time origin.
See also the documentation details of pm_timer.
Parameters
[in] since : The input scalar of type real of kind double precision RKD representing the time origin (epoch) in seconds.
(optional. If not present, its value is processor-dependent but constant at runtime.)
Returns
timeInSec : The output scalar of type real of kind double precision RKD, containing the time in seconds since a processor-defined origin of time.
Possible calling interfaces ⛓
use pm_timer, only: getTimeSYS
real(RKD) :: timeInSec
timeInSec = getTimeSYS(since = since)
Remarks
The procedures under discussion are impure.
See also
timerSYS_type
Example usage ⛓
program example
    use pm_kind, only: SK, IK, LK, RKD
    use pm_io, only: display_type
    use pm_timer, only: getTimeSYS
    use pm_timer, only: setIdleSYS
    implicit none
    real(RKD)           :: since
    type(display_type)  :: disp
    disp = display_type(file = "main.out.F90")
    call disp%skip()
    call disp%show("since = getTimeSYS()")
                    since = getTimeSYS()
    call disp%show("call setIdleSYS(seconds = 0.1_RKD)")
                    call setIdleSYS(seconds = 0.1_RKD)
    call disp%show("getTimeSYS(since)")
    call disp%show( getTimeSYS(since) )
    call disp%skip()
end program example
Example Unix compile command via Intel ifort compiler ⛓
#!/usr/bin/env sh
rm main.exe
ifort -fpp -standard-semantics -O3 -Wl,-rpath,../../../lib -I../../../inc main.F90 ../../../lib/libparamonte_fortran_*_intel* -o main.exe
./main.exe
Example Windows Batch compile command via Intel ifort compiler ⛓
del main.exe
set PATH=..\..\..\lib;%PATH%
ifort /fpp /standard-semantics /O3 /I:..\..\..\include main.F90 ..\..\..\lib\libparamonte_fortran_*_intel*.lib /exe:main.exe
main.exe
Example Unix / MinGW compile command via GNU gfortran compiler ⛓
#!/usr/bin/env sh
rm main.exe
gfortran -cpp -ffree-line-length-none -O3 -Wl,-rpath,../../../lib -I../../../inc main.F90 ../../../lib/libparamonte_fortran_*_gnu* -o main.exe
./main.exe
Example output ⛓
since = getTimeSYS()
call setIdleSYS(seconds = 0.1_RKD)
getTimeSYS(since)
+0.10005266297957860
Test:
test_pm_timer
Todo:
Normal Priority: The performance of this procedure could be improved by avoiding the unnecessary retrieval of the count rate and computing its inverse to get the period (which is fixed in the entire runtime).
This requires redefining this procedure as a type-bound procedure of a parent timer type.
However, preliminary benchmarks indicate that the division (instead of multiplication) slows down the computation by at most 25 percent. On modern architecture, the extra cost is likely on the of 25 CPU cycles, approximately 25 nanoseconds. This is likely negligible in most practical scenarios. Here is a benchmark script for the cost of division vs. multiplication,
implicit none
double precision :: t0, t1, x(2), summ
integer :: v0(8), v1(8)
integer :: i
call cpu_time(t0)
!call date_and_time(values = v0)
do i = 1, 10**7
    call random_number(x)
    summ = summ + x(2) * x(1)
end do
call cpu_time(t1)
print *, summ, "prod", t1 - t0
!call date_and_time(values = v1)
!print *, summ, "prod", v1(7) - v0(7) + (v1(8) - v0(8)) / 1.d3
summ = 0.d0
call cpu_time(t0)
!call date_and_time(values = v0)
do i = 1, 10**7
    call random_number(x)
    summ = summ + x(2) / x(1)
end do
!call date_and_time(values = v1)
call cpu_time(t1)
print *, summ, t1 - t0
!print *, summ, "divi", v1(7) - v0(7) + (v1(8) - v0(8)) / 1.d3
end
The above code yields highly similar time costs for multiplication vs. division operation in most benchmarks.
Final Remarks ⛓
If you believe this algorithm or its documentation can be improved, we appreciate your contribution and help to edit this page's documentation and source file on GitHub.
For details on the naming abbreviations, see this page.
For details on the naming conventions, see this page.
This software is distributed under the MIT license with additional terms outlined below.
If you use any parts or concepts from this library to any extent, you must acknowledge the usage by citing the relevant publications of the ParaMonte library.
If you regenerate any parts/ideas from this library in a programming environment other than those currently supported by this ParaMonte library (i.e., other than C, C++, Fortran, MATLAB, Python, R), you must also ask the end users to cite this original ParaMonte library.
Copyright
Computational Data Science Lab
Author:
Amir Shahmoradi, March 22, 2012, 00:00 AM, National Institute for Fusion Studies, The University of Texas at Austin
Definition at line 1197 of file pm_timer.F90.
Referenced by getTime(), and setIdleSYS().
setIdle()
subroutine pm_timer::setIdle (real(RKD), intent(in) seconds)
Set the processor in sleep mode for the input requested number of seconds via the default timer of the ParaMonte library.
This function relies on either of the following lower-level module functions depending on the ParaMonte library build:
setIdleMPI for MPI-enabled parallel builds of the ParaMonte library.
setIdleOMP for OpenMP-enabled parallel builds of the ParaMonte library.
setIdleSYS for all other parallel or serial builds of the ParaMonte library.
Parameters
[in] seconds : The input scalar of type real of kind double precision RKD representing the number of seconds to put the system into sleep.
Possible calling interfaces ⛓
use pm_timer, only: setIdle
real(RKD) :: seconds
call setIdle(seconds)
Remarks
The procedures under discussion are impure.
See also
setIdleCPU
setIdleDAT
setIdleMPI
setIdleOMP
setIdleSYS
getTimeCPU
getTimeDAT
getTimeMPI
getTimeOMP
getTimeSYS
Example usage ⛓
program example
    use pm_kind, only: SK, IK, LK, RKD
    use pm_io, only: display_type
    use pm_timer, only: getTime
    use pm_timer, only: setIdle
    implicit none
    real(RKD)           :: since
    type(display_type)  :: disp
    disp = display_type(file = "main.out.F90")
    call disp%skip()
    call disp%show("since = getTime()")
                    since = getTime()
    call disp%show("call setIdle(seconds = 0.2_RKD)")
                    call setIdle(seconds = 0.2_RKD)
    call disp%show("getTime(since)")
    call disp%show( getTime(since) )
    call disp%skip()
end program example
Example Unix compile command via Intel ifort compiler ⛓
#!/usr/bin/env sh
rm main.exe
ifort -fpp -standard-semantics -O3 -Wl,-rpath,../../../lib -I../../../inc main.F90 ../../../lib/libparamonte_fortran_*_intel* -o main.exe
./main.exe
Example Windows Batch compile command via Intel ifort compiler ⛓
del main.exe
set PATH=..\..\..\lib;%PATH%
ifort /fpp /standard-semantics /O3 /I:..\..\..\include main.F90 ..\..\..\lib\libparamonte_fortran_*_intel*.lib /exe:main.exe
main.exe
Example Unix / MinGW compile command via GNU gfortran compiler ⛓
#!/usr/bin/env sh
rm main.exe
gfortran -cpp -ffree-line-length-none -O3 -Wl,-rpath,../../../lib -I../../../inc main.F90 ../../../lib/libparamonte_fortran_*_gnu* -o main.exe
./main.exe
Example output ⛓
since = getTime()
call setIdle(seconds = 0.2_RKD)
getTime(since)
+0.20004870599950664
Test:
test_pm_timer
Final Remarks ⛓
If you believe this algorithm or its documentation can be improved, we appreciate your contribution and help to edit this page's documentation and source file on GitHub.
For details on the naming abbreviations, see this page.
For details on the naming conventions, see this page.
This software is distributed under the MIT license with additional terms outlined below.
If you use any parts or concepts from this library to any extent, you must acknowledge the usage by citing the relevant publications of the ParaMonte library.
If you regenerate any parts/ideas from this library in a programming environment other than those currently supported by this ParaMonte library (i.e., other than C, C++, Fortran, MATLAB, Python, R), you must also ask the end users to cite this original ParaMonte library.
Copyright
Computational Data Science Lab
Author:
Amir Shahmoradi, March 22, 2012, 00:00 AM, National Institute for Fusion Studies, The University of Texas at Austin
Definition at line 1592 of file pm_timer.F90.
References pm_kind::RKD, setIdleMPI(), setIdleOMP(), and setIdleSYS().
setIdleCPU()
subroutine pm_timer::setIdleCPU (real(RKD), intent(in) seconds)
Set the processor in sleep mode for the input requested number of seconds via the Fortran intrinsic cpu_time().
Parameters
[in] seconds : The input scalar of type real of kind double precision RKD representing the number of seconds to put the system into sleep.
Possible calling interfaces ⛓
use pm_timer, only: setIdleCPU
real(RKD) :: seconds
call setIdleCPU(seconds)
Warning
If the system does not possess a clock, the results are unpredictable and the procedure may enter an indefinite loop.
However, this condition rarely occurs and can be readily check only once on each new platform before a production run.
The lack of a system clock will lead to runtime error only if the library is built with the preprocessor macro CHECK_ENABLED=1.
Remarks
The procedures under discussion are impure.
See also
setIdleCPU
setIdleDAT
setIdleMPI
setIdleOMP
setIdleSYS
getTimeCPU
getTimeDAT
getTimeMPI
getTimeOMP
getTimeSYS
Example usage ⛓
program example
    use pm_kind, only: SK, IK, LK, RKD
    use pm_io, only: display_type
    use pm_timer, only: getTimeCPU
    use pm_timer, only: setIdleCPU
    implicit none
    real(RKD)           :: since
    type(display_type)  :: disp
    disp = display_type(file = "main.out.F90")
    call disp%skip()
    call disp%show("since = getTimeCPU()")
                    since = getTimeCPU()
    call disp%show("call setIdleCPU(seconds = 0.1_RKD)")
                    call setIdleCPU(seconds = 0.1_RKD)
    call disp%show("getTimeCPU(since)")
    call disp%show( getTimeCPU(since) )
    call disp%skip()
end program example
Example Unix compile command via Intel ifort compiler ⛓
#!/usr/bin/env sh
rm main.exe
ifort -fpp -standard-semantics -O3 -Wl,-rpath,../../../lib -I../../../inc main.F90 ../../../lib/libparamonte_fortran_*_intel* -o main.exe
./main.exe
Example Windows Batch compile command via Intel ifort compiler ⛓
del main.exe
set PATH=..\..\..\lib;%PATH%
ifort /fpp /standard-semantics /O3 /I:..\..\..\include main.F90 ..\..\..\lib\libparamonte_fortran_*_intel*.lib /exe:main.exe
main.exe
Example Unix / MinGW compile command via GNU gfortran compiler ⛓
#!/usr/bin/env sh
rm main.exe
gfortran -cpp -ffree-line-length-none -O3 -Wl,-rpath,../../../lib -I../../../inc main.F90 ../../../lib/libparamonte_fortran_*_gnu* -o main.exe
./main.exe
Example output ⛓
since = getTimeCPU()
call setIdleCPU(seconds = 0.1_RKD)
getTimeCPU(since)
+0.10002400000000000
Test:
test_pm_timer
Final Remarks ⛓
If you believe this algorithm or its documentation can be improved, we appreciate your contribution and help to edit this page's documentation and source file on GitHub.
For details on the naming abbreviations, see this page.
For details on the naming conventions, see this page.
This software is distributed under the MIT license with additional terms outlined below.
If you use any parts or concepts from this library to any extent, you must acknowledge the usage by citing the relevant publications of the ParaMonte library.
If you regenerate any parts/ideas from this library in a programming environment other than those currently supported by this ParaMonte library (i.e., other than C, C++, Fortran, MATLAB, Python, R), you must also ask the end users to cite this original ParaMonte library.
Copyright
Computational Data Science Lab
Author:
Amir Shahmoradi, March 22, 2012, 00:00 AM, National Institute for Fusion Studies, The University of Texas at Austin
Definition at line 1657 of file pm_timer.F90.
References getTimeCPU(), and pm_kind::RKD.
setIdleDAT()
subroutine pm_timer::setIdleDAT (real(RKD), intent(in) seconds)
Set the processor in sleep mode for the input requested number of seconds via the Fortran intrinsic date_and_time().
Parameters
[in] seconds : The input scalar of type real of kind double precision RKD representing the number of seconds to put the system into sleep.
Possible calling interfaces ⛓
use pm_timer, only: setIdleDAT
real(RKD) :: seconds
call setIdleDAT(seconds)
Warning
If the system does not possess a clock, the results are unpredictable and the procedure may enter an indefinite loop.
However, this condition rarely occurs and can be readily check only once on each new platform before a production run.
The lack of a system clock will lead to runtime error only if the library is built with the preprocessor macro CHECK_ENABLED=1.
Remarks
The procedures under discussion are impure.
See also
setIdleCPU
setIdleDAT
setIdleMPI
setIdleOMP
setIdleSYS
getTimeCPU
getTimeDAT
getTimeMPI
getTimeOMP
getTimeSYS
Example usage ⛓
program example
    use pm_kind, only: SK, IK, LK, RKD
    use pm_io, only: display_type
    use pm_timer, only: getTimeDAT
    use pm_timer, only: setIdleDAT
    implicit none
    real(RKD)           :: since
    type(display_type)  :: disp
    disp = display_type(file = "main.out.F90")
    call disp%skip()
    call disp%show("since = getTimeDAT()")
                    since = getTimeDAT()
    call disp%show("call setIdleDAT(seconds = 0.2_RKD)")
                    call setIdleDAT(seconds = 0.2_RKD)
    call disp%show("getTimeDAT(since)")
    call disp%show( getTimeDAT(since) )
    call disp%skip()
end program example
Example Unix compile command via Intel ifort compiler ⛓
#!/usr/bin/env sh
rm main.exe
ifort -fpp -standard-semantics -O3 -Wl,-rpath,../../../lib -I../../../inc main.F90 ../../../lib/libparamonte_fortran_*_intel* -o main.exe
./main.exe
Example Windows Batch compile command via Intel ifort compiler ⛓
del main.exe
set PATH=..\..\..\lib;%PATH%
ifort /fpp /standard-semantics /O3 /I:..\..\..\include main.F90 ..\..\..\lib\libparamonte_fortran_*_intel*.lib /exe:main.exe
main.exe
Example Unix / MinGW compile command via GNU gfortran compiler ⛓
#!/usr/bin/env sh
rm main.exe
gfortran -cpp -ffree-line-length-none -O3 -Wl,-rpath,../../../lib -I../../../inc main.F90 ../../../lib/libparamonte_fortran_*_gnu* -o main.exe
./main.exe
Example output ⛓
since = getTimeDAT()
call setIdleDAT(seconds = 0.2_RKD)
getTimeDAT(since)
+0.20098876953125000
Test:
test_pm_timer
Final Remarks ⛓
If you believe this algorithm or its documentation can be improved, we appreciate your contribution and help to edit this page's documentation and source file on GitHub.
For details on the naming abbreviations, see this page.
For details on the naming conventions, see this page.
This software is distributed under the MIT license with additional terms outlined below.
If you use any parts or concepts from this library to any extent, you must acknowledge the usage by citing the relevant publications of the ParaMonte library.
If you regenerate any parts/ideas from this library in a programming environment other than those currently supported by this ParaMonte library (i.e., other than C, C++, Fortran, MATLAB, Python, R), you must also ask the end users to cite this original ParaMonte library.
Copyright
Computational Data Science Lab
Author:
Amir Shahmoradi, March 22, 2012, 00:00 AM, National Institute for Fusion Studies, The University of Texas at Austin
Definition at line 1720 of file pm_timer.F90.
References getTimeDAT(), and pm_kind::RKD.
setIdleMPI()
subroutine pm_timer::setIdleMPI (real(RKD), intent(in) seconds)
Set the processor in sleep mode for the input requested number of seconds via the MPI intrinsic timer MPI_Wtime().
Parameters
[in] seconds : The input scalar of type real of kind double precision RKD representing the number of seconds to put the system into sleep.
Possible calling interfaces ⛓
use pm_timer, only: setIdleMPI
real(RKD) :: seconds
call setIdleMPI(seconds)
Warning
This procedure exists only if the library is built with the preprocessor macro MPI_ENABLED=1.
Calling this procedure requires the MPI library to have been initialized and not finalized.
This condition is verified only if the library is built with the preprocessor macro CHECK_ENABLED=1.
Remarks
The procedures under discussion are impure.
See also
setIdleCPU
setIdleDAT
setIdleMPI
setIdleOMP
setIdleSYS
getTimeCPU
getTimeDAT
getTimeMPI
getTimeOMP
getTimeSYS
Example usage ⛓
program example
    use pm_kind, only: SK, IK, LK, RKD
    use pm_io, only: display_type
    implicit none
    type(display_type)  :: disp
    disp = display_type(file = "main.out.F90")
#if defined MPI_VERSION
    block
        use pm_timer, only: getTimeMPI
        use pm_timer, only: setIdleMPI
        real(RKD) :: since
        call disp%skip()
        call disp%show("since = getTimeMPI()")
                        since = getTimeMPI()
        call disp%show("call setIdleMPI(seconds = 0.2_RKD)")
                        call setIdleMPI(seconds = 0.2_RKD)
        call disp%show("getTimeMPI(since)")
        call disp%show( getTimeMPI(since) )
        call disp%skip()
    end block
#else
    call disp%show("The MPI timer is unavailable, because this example has not been linked with an MPI library.")
#endif
end program example
Example Unix compile command via Intel ifort compiler ⛓
#!/usr/bin/env sh
rm main.exe
ifort -fpp -standard-semantics -O3 -Wl,-rpath,../../../lib -I../../../inc main.F90 ../../../lib/libparamonte_fortran_*_intel* -o main.exe
./main.exe
Example Windows Batch compile command via Intel ifort compiler ⛓
del main.exe
set PATH=..\..\..\lib;%PATH%
ifort /fpp /standard-semantics /O3 /I:..\..\..\include main.F90 ..\..\..\lib\libparamonte_fortran_*_intel*.lib /exe:main.exe
main.exe
Example Unix / MinGW compile command via GNU gfortran compiler ⛓
#!/usr/bin/env sh
rm main.exe
gfortran -cpp -ffree-line-length-none -O3 -Wl,-rpath,../../../lib -I../../../inc main.F90 ../../../lib/libparamonte_fortran_*_gnu* -o main.exe
./main.exe
Example output ⛓
The MPI timer is unavailable, because this example has not been linked with an MPI library.
Test:
test_pm_timer
Final Remarks ⛓
If you believe this algorithm or its documentation can be improved, we appreciate your contribution and help to edit this page's documentation and source file on GitHub.
For details on the naming abbreviations, see this page.
For details on the naming conventions, see this page.
This software is distributed under the MIT license with additional terms outlined below.
If you use any parts or concepts from this library to any extent, you must acknowledge the usage by citing the relevant publications of the ParaMonte library.
If you regenerate any parts/ideas from this library in a programming environment other than those currently supported by this ParaMonte library (i.e., other than C, C++, Fortran, MATLAB, Python, R), you must also ask the end users to cite this original ParaMonte library.
Copyright
Computational Data Science Lab
Author:
Amir Shahmoradi, March 22, 2012, 00:00 AM, National Institute for Fusion Studies, The University of Texas at Austin
Definition at line 1786 of file pm_timer.F90.
References getTimeMPI(), and pm_kind::RKD.
Referenced by setIdle().
setIdleOMP()
subroutine pm_timer::setIdleOMP (real(RKD), intent(in) seconds)
Set the processor in sleep mode for the input requested number of seconds via the OpenMP intrinsic timer omp_get_wtime().
Parameters
[in] seconds : The input scalar of type real of kind double precision RKD representing the number of seconds to put the system into sleep.
Possible calling interfaces ⛓
use pm_timer, only: setIdleOMP
real(RKD) :: seconds
call setIdleOMP(seconds)
Warning
This procedure exists only if the library is built with the preprocessor macro OMP_ENABLED=1.
Remarks
The procedures under discussion are impure.
See also
setIdleCPU
setIdleDAT
setIdleMPI
setIdleOMP
setIdleSYS
getTimeCPU
getTimeDAT
getTimeMPI
getTimeOMP
getTimeSYS
Example usage ⛓
program example
    use pm_kind, only: SK, IK, LK, RKD
    use pm_io, only: display_type
    implicit none
    type(display_type)  :: disp
    disp = display_type(file = "main.out.F90")
#if defined _OPENMP
    block
        use pm_timer, only: getTimeOMP
        use pm_timer, only: setIdleOMP
        real(RKD)           :: since
        call disp%skip()
        call disp%show("since = getTimeOMP()")
                        since = getTimeOMP()
        call disp%show("call setIdleOMP(seconds = 0.2_RKD)")
                        call setIdleOMP(seconds = 0.2_RKD)
        call disp%show("getTimeOMP(since)")
        call disp%show( getTimeOMP(since) )
        call disp%skip()
    end block
#else
    call disp%show("The OMP timer is unavailable, because this example has not been linked with an OpenMP library.")
#endif
end program example
Example Unix compile command via Intel ifort compiler ⛓
#!/usr/bin/env sh
rm main.exe
ifort -fpp -standard-semantics -O3 -Wl,-rpath,../../../lib -I../../../inc main.F90 ../../../lib/libparamonte_fortran_*_intel* -o main.exe
./main.exe
Example Windows Batch compile command via Intel ifort compiler ⛓
del main.exe
set PATH=..\..\..\lib;%PATH%
ifort /fpp /standard-semantics /O3 /I:..\..\..\include main.F90 ..\..\..\lib\libparamonte_fortran_*_intel*.lib /exe:main.exe
main.exe
Example Unix / MinGW compile command via GNU gfortran compiler ⛓
#!/usr/bin/env sh
rm main.exe
gfortran -cpp -ffree-line-length-none -O3 -Wl,-rpath,../../../lib -I../../../inc main.F90 ../../../lib/libparamonte_fortran_*_gnu* -o main.exe
./main.exe
Example output ⛓
The OMP timer is unavailable, because this example has not been linked with an OpenMP library.
Test:
test_pm_timer
Final Remarks ⛓
If you believe this algorithm or its documentation can be improved, we appreciate your contribution and help to edit this page's documentation and source file on GitHub.
For details on the naming abbreviations, see this page.
For details on the naming conventions, see this page.
This software is distributed under the MIT license with additional terms outlined below.
If you use any parts or concepts from this library to any extent, you must acknowledge the usage by citing the relevant publications of the ParaMonte library.
If you regenerate any parts/ideas from this library in a programming environment other than those currently supported by this ParaMonte library (i.e., other than C, C++, Fortran, MATLAB, Python, R), you must also ask the end users to cite this original ParaMonte library.
Copyright
Computational Data Science Lab
Author:
Amir Shahmoradi, March 22, 2012, 00:00 AM, National Institute for Fusion Studies, The University of Texas at Austin
Definition at line 1849 of file pm_timer.F90.
References getTimeOMP(), and pm_kind::RKD.
Referenced by setIdle().
setIdleSYS()
subroutine pm_timer::setIdleSYS (real(RKD), intent(in) seconds)
Set the processor in sleep mode for the input requested number of seconds via the Fortran intrinsic system_clock().
Parameters
[in] seconds : The input scalar of type real of kind double precision RKD representing the number of seconds to put the system into sleep.
Possible calling interfaces ⛓
use pm_timer, only: setIdleSYS
real(RKD) :: seconds
call setIdleSYS(seconds)
Warning
If the system does not possess a clock, the results are unpredictable and the procedure may enter an indefinite loop.
However, this condition rarely occurs and can be readily check only once on each new platform before a production run.
The lack of a system clock will lead to runtime error only if the library is built with the preprocessor macro CHECK_ENABLED=1.
Remarks
The procedures under discussion are impure.
See also
setIdleCPU
setIdleDAT
setIdleMPI
setIdleOMP
setIdleSYS
getTimeCPU
getTimeDAT
getTimeMPI
getTimeOMP
getTimeSYS
Example usage ⛓
program example
    use pm_kind, only: SK, IK, LK, RKD
    use pm_io, only: display_type
    use pm_timer, only: getTimeSYS
    use pm_timer, only: setIdleSYS
    implicit none
    real(RKD)           :: since
    type(display_type)  :: disp
    disp = display_type(file = "main.out.F90")
    call disp%skip()
    call disp%show("since = getTimeSYS()")
                    since = getTimeSYS()
    call disp%show("call setIdleSYS(seconds = 0.2_RKD)")
                    call setIdleSYS(seconds = 0.2_RKD)
    call disp%show("getTimeSYS(since)")
    call disp%show( getTimeSYS(since) )
    call disp%skip()
end program example
Example Unix compile command via Intel ifort compiler ⛓
#!/usr/bin/env sh
rm main.exe
ifort -fpp -standard-semantics -O3 -Wl,-rpath,../../../lib -I../../../inc main.F90 ../../../lib/libparamonte_fortran_*_intel* -o main.exe
./main.exe
Example Windows Batch compile command via Intel ifort compiler ⛓
del main.exe
set PATH=..\..\..\lib;%PATH%
ifort /fpp /standard-semantics /O3 /I:..\..\..\include main.F90 ..\..\..\lib\libparamonte_fortran_*_intel*.lib /exe:main.exe
main.exe
Example Unix / MinGW compile command via GNU gfortran compiler ⛓
#!/usr/bin/env sh
rm main.exe
gfortran -cpp -ffree-line-length-none -O3 -Wl,-rpath,../../../lib -I../../../inc main.F90 ../../../lib/libparamonte_fortran_*_gnu* -o main.exe
./main.exe
Example output ⛓
since = getTimeSYS()
call setIdleSYS(seconds = 0.2_RKD)
getTimeSYS(since)
+0.20003647301928140
Test:
test_pm_timer
Final Remarks ⛓
If you believe this algorithm or its documentation can be improved, we appreciate your contribution and help to edit this page's documentation and source file on GitHub.
For details on the naming abbreviations, see this page.
For details on the naming conventions, see this page.
This software is distributed under the MIT license with additional terms outlined below.
If you use any parts or concepts from this library to any extent, you must acknowledge the usage by citing the relevant publications of the ParaMonte library.
If you regenerate any parts/ideas from this library in a programming environment other than those currently supported by this ParaMonte library (i.e., other than C, C++, Fortran, MATLAB, Python, R), you must also ask the end users to cite this original ParaMonte library.
Copyright
Computational Data Science Lab
Author:
Amir Shahmoradi, March 22, 2012, 00:00 AM, National Institute for Fusion Studies, The University of Texas at Austin
Definition at line 1913 of file pm_timer.F90.
References getTimeSYS(), and pm_kind::RKD.
Referenced by setIdle().
timer_typer()
type(timerMPI_type) type(timerOMP_type) type(timerSYS_type) function pm_timer::timer_typer
This is the constructor of the timer_type class.
Upon return, the constructor initializes all components of the timer object.
See also the documentation details of pm_timer.
Returns
timer : The output scalar object of class timer_type.
Specifically, the output of type,
timerMPI_type if the ParaMonte library is built with preprocessor macro MPI_ENABLED defined.
timerOMP_type if the ParaMonte library is built with preprocessor macro OMP_ENABLED defined.
timerSYS_type if the ParaMonte library is built is serial mode.
Possible calling interfaces ⛓
use pm_timer, only: timer_type
class(timer_type), allocatable :: timer
timer = timer_type()
Remarks
See the documentation of timer_type for example usage.
Final Remarks ⛓
If you believe this algorithm or its documentation can be improved, we appreciate your contribution and help to edit this page's documentation and source file on GitHub.
For details on the naming abbreviations, see this page.
For details on the naming conventions, see this page.
This software is distributed under the MIT license with additional terms outlined below.
If you use any parts or concepts from this library to any extent, you must acknowledge the usage by citing the relevant publications of the ParaMonte library.
If you regenerate any parts/ideas from this library in a programming environment other than those currently supported by this ParaMonte library (i.e., other than C, C++, Fortran, MATLAB, Python, R), you must also ask the end users to cite this original ParaMonte library.
Copyright
Computational Data Science Lab
Author:
Amir Shahmoradi, March 22, 2012, 00:00 AM, National Institute for Fusion Studies, The University of Texas at Austin
Definition at line 556 of file pm_timer.F90.
timerCPU_typer()
type(timerCPU_type) function pm_timer::timerCPU_typer
This is the constructor of the timerCPU_type class.
Upon return, the constructor initializes all components of the timer object.
See also the documentation details of pm_timer.
Returns
timer : The output scalar object of class timerCPU_type.
Possible calling interfaces ⛓
use pm_timer, only: timerCPU_type
type(timerCPU_type) :: timer
timer = timerCPU_type()
Remarks
See the documentation of timerCPU_type for example usage.
Final Remarks ⛓
If you believe this algorithm or its documentation can be improved, we appreciate your contribution and help to edit this page's documentation and source file on GitHub.
For details on the naming abbreviations, see this page.
For details on the naming conventions, see this page.
This software is distributed under the MIT license with additional terms outlined below.
If you use any parts or concepts from this library to any extent, you must acknowledge the usage by citing the relevant publications of the ParaMonte library.
If you regenerate any parts/ideas from this library in a programming environment other than those currently supported by this ParaMonte library (i.e., other than C, C++, Fortran, MATLAB, Python, R), you must also ask the end users to cite this original ParaMonte library.
Copyright
Computational Data Science Lab
Author:
Amir Shahmoradi, March 22, 2012, 00:00 AM, National Institute for Fusion Studies, The University of Texas at Austin
Definition at line 601 of file pm_timer.F90.
timerDAT_typer()
type(timerDAT_type) function pm_timer::timerDAT_typer
This is the constructor of the timerDAT_type class.
Upon return, the constructor initializes all components of the timer object.
See also the documentation details of pm_timer.
Possible calling interfaces ⛓
use pm_timer, only: timerDAT_type
type(timerDAT_type) :: timer
timer = timerDAT_type()
Returns
timer : The output scalar object of class timerDAT_type.
Remarks
See the documentation of timerDAT_type for example usage.
Final Remarks ⛓
If you believe this algorithm or its documentation can be improved, we appreciate your contribution and help to edit this page's documentation and source file on GitHub.
For details on the naming abbreviations, see this page.
For details on the naming conventions, see this page.
This software is distributed under the MIT license with additional terms outlined below.
If you use any parts or concepts from this library to any extent, you must acknowledge the usage by citing the relevant publications of the ParaMonte library.
If you regenerate any parts/ideas from this library in a programming environment other than those currently supported by this ParaMonte library (i.e., other than C, C++, Fortran, MATLAB, Python, R), you must also ask the end users to cite this original ParaMonte library.
Copyright
Computational Data Science Lab
Author:
Amir Shahmoradi, March 22, 2012, 00:00 AM, National Institute for Fusion Studies, The University of Texas at Austin
Definition at line 641 of file pm_timer.F90.
timerMPI_typer()
type(timerMPI_type) function pm_timer::timerMPI_typer
This is the constructor of the timerMPI_type class.
Upon return, the constructor initializes all components of the timer object.
See also the documentation details of pm_timer.
Possible calling interfaces ⛓
use pm_timer, only: timerMPI_type
type(timerMPI_type) :: timer
timer = timerMPI_type()
Returns
timer : The output scalar object of class timerMPI_type.
Warning
This constructor requires the MPI library to have been initialized and not finalized.
This condition is verified only if the library is built with the preprocessor macro CHECK_ENABLED=1.
This constructor is available only if the library is built with the preprocessor macro MPI_ENABLED=1.
Remarks
See the documentation of timerMPI_type for example usage.
Final Remarks ⛓
If you believe this algorithm or its documentation can be improved, we appreciate your contribution and help to edit this page's documentation and source file on GitHub.
For details on the naming abbreviations, see this page.
For details on the naming conventions, see this page.
This software is distributed under the MIT license with additional terms outlined below.
If you use any parts or concepts from this library to any extent, you must acknowledge the usage by citing the relevant publications of the ParaMonte library.
If you regenerate any parts/ideas from this library in a programming environment other than those currently supported by this ParaMonte library (i.e., other than C, C++, Fortran, MATLAB, Python, R), you must also ask the end users to cite this original ParaMonte library.
Copyright
Computational Data Science Lab
Author:
Amir Shahmoradi, March 22, 2012, 02:51 AM, National Institute for Fusion Studies, The University of Texas at Austin
Definition at line 689 of file pm_timer.F90.
timerOMP_typer()
type(timerOMP_type) function pm_timer::timerOMP_typer
This is the constructor of the timerOMP_type class.
Upon return, the constructor initializes all components of the timer object.
See also the documentation details of pm_timer.
Possible calling interfaces ⛓
use pm_timer, only: timerOMP_type
type(timerOMP_type) :: timer
timer = timerOMP_type()
Returns
timer : The output scalar object of class timerOMP_type.
Warning
This constructor is available only if the library is built with the preprocessor macro OMP_ENABLED=1.
Remarks
See the documentation of timerOMP_type for example usage.
Final Remarks ⛓
If you believe this algorithm or its documentation can be improved, we appreciate your contribution and help to edit this page's documentation and source file on GitHub.
For details on the naming abbreviations, see this page.
For details on the naming conventions, see this page.
This software is distributed under the MIT license with additional terms outlined below.
If you use any parts or concepts from this library to any extent, you must acknowledge the usage by citing the relevant publications of the ParaMonte library.
If you regenerate any parts/ideas from this library in a programming environment other than those currently supported by this ParaMonte library (i.e., other than C, C++, Fortran, MATLAB, Python, R), you must also ask the end users to cite this original ParaMonte library.
Copyright
Computational Data Science Lab
Author:
Amir Shahmoradi, March 22, 2012, 00:00 AM, National Institute for Fusion Studies, The University of Texas at Austin
Definition at line 752 of file pm_timer.F90.
timerSYS_typer()
type(timerSYS_type) function pm_timer::timerSYS_typer
This is the constructor of the timerSYS_type class.
Upon return, the constructor initializes all components of the timer object.
See also the documentation details of pm_timer.
Possible calling interfaces ⛓
use pm_timer, only: timerSYS_type
type(timerSYS_type) :: timer
timer = timerSYS_type()
Returns
timer : The output scalar object of class timerSYS_type.
Remarks
See the documentation of timerSYS_type for example usage.
Final Remarks ⛓
If you believe this algorithm or its documentation can be improved, we appreciate your contribution and help to edit this page's documentation and source file on GitHub.
For details on the naming abbreviations, see this page.
For details on the naming conventions, see this page.
This software is distributed under the MIT license with additional terms outlined below.
If you use any parts or concepts from this library to any extent, you must acknowledge the usage by citing the relevant publications of the ParaMonte library.
If you regenerate any parts/ideas from this library in a programming environment other than those currently supported by this ParaMonte library (i.e., other than C, C++, Fortran, MATLAB, Python, R), you must also ask the end users to cite this original ParaMonte library.
Copyright
Computational Data Science Lab
Author:
Amir Shahmoradi, March 22, 2012, 03:00 AM, National Institute for Fusion Studies, The University of Texas at Austin
Definition at line 794 of file pm_timer.F90.
Variable Documentation
MODULE_NAME
character(*, SK), parameter pm_timer::MODULE_NAME = "@pm_timer"
Definition at line 117 of file pm_timer.F90.