ParaMonte Fortran 2.0.0: test_pm_strASCII Module Reference
test_pm_strASCII Module Reference
This module contains tests of the module pm_strASCII.
Functions/Subroutines
logical(LK) function test_getLocSpace_1 ()
logical(LK) function test_isCharDigit_1 ()
logical(LK) function test_isStrDigitAll_1 ()
logical(LK) function test_isStrReal_1 ()
logical(LK) function test_isStrInteger_1 ()
logical(LK) function test_isStrNumber_1 ()
logical(LK) function test_isCharLower_1 ()
logical(LK) function test_isCharUpper_1 ()
logical(LK) function test_isStrLowerAll_1 ()
logical(LK) function test_isStrUpperAll_1 ()
logical(LK) function test_isStrAlphaNumAll_1 ()
logical(LK) function test_isStrAlpha_1 ()
logical(LK) function test_getStrLower_1 ()
logical(LK) function test_getStrUpper_1 ()
logical(LK) function test_setStrLower_1 ()
logical(LK) function test_setStrUpper_1 ()
logical(LK) function test_isStrComplex_1 ()
character(:, SK) function, allocatable getComplexStr (lp, rp, sep)
This is a helper function for generating valid complex values in string format, used to verify the functionality of isStrComplex.
character(:, SK) function, allocatable getNonComplexStr ()
This is a helper function for generating invalid complex values in string format, used to verify the functionality of isStrComplex.
character(:, SK) function, allocatable getRealStr ()
This is a helper function for generating valid real values in string format, used to verify the functionality of isStrReal.
character(:, SK) function, allocatable getNonRealStr ()
This is a helper function for generating invalid real values in string format, used to verify the functionality of isStrReal.
subroutine setData ()
Define the global testing data.
subroutine setTest ()
Variables
type(test_type) test
type(strc), dimension(:), allocatable NonIntSet
type(strc), dimension(:), allocatable IntSet
type(strc), dimension(:), allocatable RealSet
type(strc), dimension(:), allocatable NonRealSet
Detailed Description
This module contains tests of the module pm_strASCII.
Final Remarks ⛓
If you believe this algorithm or its documentation can be improved, we appreciate your contribution and help to edit this page's documentation and source file on GitHub.
For details on the naming abbreviations, see this page.
For details on the naming conventions, see this page.
This software is distributed under the MIT license with additional terms outlined below.
If you use any parts or concepts from this library to any extent, please acknowledge the usage by citing the relevant publications of the ParaMonte library.
If you regenerate any parts/ideas from this library in a programming environment other than those currently supported by this ParaMonte library (i.e., other than C, C++, Fortran, MATLAB, Python, R), please also ask the end users to cite this original ParaMonte library.
This software is available to the public under a highly permissive license.
Help us justify its continued development and maintenance by acknowledging its benefit to society, distributing it, and contributing to it.
Copyright
Computational Data Science Lab
Author:
Amir Shahmoradi
Function/Subroutine Documentation
getComplexStr()
character(:, SK) function, allocatable test_pm_strASCII::getComplexStr (character(*, SK), intent(in), optional lp, character(*, SK), intent(in), optional rp, character(*, SK), intent(in), optional sep)
This is a helper function for generating valid complex values in string format, used to verify the functionality of isStrComplex.
Definition at line 492 of file test_pm_strASCII.F90.
References getRealStr().
Referenced by getNonComplexStr(), and test_isStrComplex_1().
getNonComplexStr()
character(:, SK) function, allocatable test_pm_strASCII::getNonComplexStr
This is a helper function for generating invalid complex values in string format, used to verify the functionality of isStrComplex.
Definition at line 513 of file test_pm_strASCII.F90.
References getComplexStr(), getNonRealStr(), and getRealStr().
Referenced by test_isStrComplex_1().
getNonRealStr()
character(:, SK) function, allocatable test_pm_strASCII::getNonRealStr
This is a helper function for generating invalid real values in string format, used to verify the functionality of isStrReal.
Definition at line 557 of file test_pm_strASCII.F90.
Referenced by getNonComplexStr().
getRealStr()
character(:, SK) function, allocatable test_pm_strASCII::getRealStr
This is a helper function for generating valid real values in string format, used to verify the functionality of isStrReal.
Definition at line 542 of file test_pm_strASCII.F90.
Referenced by getComplexStr(), and getNonComplexStr().
setData()
subroutine test_pm_strASCII::setData
Define the global testing data.
Definition at line 575 of file test_pm_strASCII.F90.
Referenced by setTest().
setTest()
subroutine test_pm_strASCII::setTest
Definition at line 656 of file test_pm_strASCII.F90.
References setData().
test_getLocSpace_1()
logical(LK) function test_pm_strASCII::test_getLocSpace_1
Definition at line 50 of file test_pm_strASCII.F90.
test_getStrLower_1()
logical(LK) function test_pm_strASCII::test_getStrLower_1
Definition at line 326 of file test_pm_strASCII.F90.
test_getStrUpper_1()
logical(LK) function test_pm_strASCII::test_getStrUpper_1
Definition at line 347 of file test_pm_strASCII.F90.
test_isCharDigit_1()
logical(LK) function test_pm_strASCII::test_isCharDigit_1
Definition at line 67 of file test_pm_strASCII.F90.
test_isCharLower_1()
logical(LK) function test_pm_strASCII::test_isCharLower_1
Definition at line 190 of file test_pm_strASCII.F90.
test_isCharUpper_1()
logical(LK) function test_pm_strASCII::test_isCharUpper_1
Definition at line 202 of file test_pm_strASCII.F90.
test_isStrAlpha_1()
logical(LK) function test_pm_strASCII::test_isStrAlpha_1
Definition at line 296 of file test_pm_strASCII.F90.
test_isStrAlphaNumAll_1()
logical(LK) function test_pm_strASCII::test_isStrAlphaNumAll_1
Definition at line 266 of file test_pm_strASCII.F90.
test_isStrComplex_1()
logical(LK) function test_pm_strASCII::test_isStrComplex_1
Definition at line 462 of file test_pm_strASCII.F90.
References getComplexStr(), and getNonComplexStr().
test_isStrDigitAll_1()
logical(LK) function test_pm_strASCII::test_isStrDigitAll_1
Definition at line 87 of file test_pm_strASCII.F90.
test_isStrInteger_1()
logical(LK) function test_pm_strASCII::test_isStrInteger_1
Definition at line 135 of file test_pm_strASCII.F90.
References IntSet, and NonIntSet.
test_isStrLowerAll_1()
logical(LK) function test_pm_strASCII::test_isStrLowerAll_1
Definition at line 214 of file test_pm_strASCII.F90.
test_isStrNumber_1()
logical(LK) function test_pm_strASCII::test_isStrNumber_1
Definition at line 154 of file test_pm_strASCII.F90.
test_isStrReal_1()
logical(LK) function test_pm_strASCII::test_isStrReal_1
Definition at line 113 of file test_pm_strASCII.F90.
References IntSet, NonRealSet, and RealSet.
test_isStrUpperAll_1()
logical(LK) function test_pm_strASCII::test_isStrUpperAll_1
Definition at line 240 of file test_pm_strASCII.F90.
test_setStrLower_1()
logical(LK) function test_pm_strASCII::test_setStrLower_1
Definition at line 368 of file test_pm_strASCII.F90.
test_setStrUpper_1()
logical(LK) function test_pm_strASCII::test_setStrUpper_1
Definition at line 388 of file test_pm_strASCII.F90.
Variable Documentation
IntSet
type(strc), dimension(:), allocatable test_pm_strASCII::IntSet
Definition at line 40 of file test_pm_strASCII.F90.
Referenced by test_isStrInteger_1(), and test_isStrReal_1().
NonIntSet
type(strc), dimension(:), allocatable test_pm_strASCII::NonIntSet
Definition at line 39 of file test_pm_strASCII.F90.
Referenced by test_isStrInteger_1().
NonRealSet
type(strc), dimension(:), allocatable test_pm_strASCII::NonRealSet
Definition at line 42 of file test_pm_strASCII.F90.
Referenced by test_isStrReal_1().
RealSet
type(strc), dimension(:), allocatable test_pm_strASCII::RealSet
Definition at line 41 of file test_pm_strASCII.F90.
Referenced by test_isStrReal_1().
test
type(test_type) test_pm_strASCII::test
Definition at line 37 of file test_pm_strASCII.F90.