ParaMonte Fortran 2.0.0: test_pm_statest Module Reference
test_pm_statest Module Reference
This module contains tests of the module pm_statest.
Functions/Subroutines
subroutine setTest ()
logical(LK) function test_doKS1_1 ()
logical(LK) function test_getCumDenComKS_1 ()
logical(LK) function test_performance_1 ()
Compare performance of getCumDenComKS()` with pm_statest::getProbKS(). Results indicated that pm_statest::getProbKS() is approximately 2-3 times faster.
logical(LK) function test_doUniformKS1_1 ()
logical(LK) function test_doSortedKS2_1 ()
logical(LK) function test_getSampleDisparity_1 ()
Any value of SampleSize smaller than one or larger than the size of the input Point should lead to an error.
logical(LK) function test_getSampleDisparity_2 ()
Any value of SampleSize smaller than one or larger than the size of the input Point should lead to an error.
subroutine test_Uniformity ()
Variables
type(test_type) test
integer(IK), parameter lenRnd = 50_IK
real(RK), dimension(lenRnd) UnifRnd = [ 0.0759666916908419_RK , 0.2399161535536580_RK , 0.1233189348351660_RK , 0.1839077882824170_RK , 0.2399525256649030_RK , 0.4172670690843700_RK , 0.0496544303257421_RK , 0.9027161099152810_RK , 0.9447871897216460_RK , 0.4908640924680800_RK , 0.4892526384000190_RK , 0.3377194098213770_RK , 0.9000538464176620_RK , 0.3692467811202150_RK , 0.1112027552937870_RK , 0.7802520683211380_RK , 0.3897388369612530_RK , 0.2416912859138330_RK , 0.4039121455881150_RK , 0.0964545251683886_RK , 0.1319732926063350_RK , 0.9420505907754850_RK , 0.9561345402298020_RK , 0.5752085950784660_RK , 0.0597795429471558_RK , 0.2347799133724060_RK , 0.3531585712220710_RK , 0.8211940401979590_RK , 0.0154034376515551_RK , 0.0430238016578078_RK , 0.1689900294627040_RK , 0.6491154749564520_RK , 0.7317223856586700_RK , 0.6477459631363070_RK , 0.4509237064309450_RK , 0.5470088922863450_RK , 0.2963208056077730_RK , 0.7446928070741560_RK , 0.1889550150325450_RK , 0.6867754333653150_RK , 0.1835111557372700_RK , 0.3684845964903370_RK , 0.6256185607296900_RK , 0.7802274351513770_RK , 0.0811257688657853_RK , 0.9293859709687300_RK , 0.7757126786084020_RK , 0.4867916324031720_RK , 0.4358585885809190_RK , 0.4467837494298060_RK ]
real(RK), dimension(lenRnd) StdNormRnd1 = [ 0.537667139546100_RK , 1.83388501459509_RK , -2.25884686100365_RK , 0.862173320368121_RK , 0.318765239858981_RK , -1.30768829630527_RK , -0.433592022305684_RK , 0.342624466538650_RK , 3.57839693972576_RK , 2.76943702988488_RK , -1.34988694015652_RK , 3.03492346633185_RK , 0.725404224946106_RK , -0.0630548731896562_RK , 0.714742903826096_RK , -0.204966058299775_RK , -0.124144348216312_RK , 1.48969760778547_RK , 1.40903448980048_RK , 1.41719241342961_RK , 0.671497133608081_RK , -1.20748692268504_RK , 0.717238651328839_RK , 1.63023528916473_RK , 0.488893770311789_RK , 1.03469300991786_RK , 0.726885133383238_RK , -0.303440924786016_RK , 0.293871467096658_RK , -0.787282803758638_RK , 0.888395631757642_RK , -1.14707010696915_RK , -1.06887045816803_RK , -0.809498694424876_RK , -2.94428416199490_RK , 1.43838029281510_RK , 0.325190539456198_RK , -0.754928319169703_RK , 1.37029854009523_RK , -1.71151641885370_RK , -0.102242446085491_RK , -0.241447041607358_RK , 0.319206739165502_RK , 0.312858596637428_RK , -0.864879917324457_RK , -0.0300512961962686_RK , -0.164879019209038_RK , 0.627707287528727_RK , 1.09326566903948_RK , 1.10927329761440_RK ]
real(RK), dimension(lenRnd) StdNormRnd2 = [ -0.863652821988714_RK , 0.0773590911304249_RK , -1.21411704361541_RK , -1.11350074148676_RK , -0.00684932810334806_RK , 1.53263030828475_RK , -0.769665913753682_RK , 0.371378812760058_RK , -0.225584402271252_RK , 1.11735613881447_RK , -1.08906429505224_RK , 0.0325574641649735_RK , 0.552527021112224_RK , 1.10061021788087_RK , 1.54421189550395_RK , 0.0859311331754255_RK , -1.49159031063761_RK , -0.742301837259857_RK , -1.06158173331999_RK , 2.35045722400204_RK , -0.615601881466894_RK , 0.748076783703985_RK , -0.192418510588264_RK , 0.888610425420721_RK , -0.764849236567874_RK , -1.40226896933876_RK , -1.42237592509150_RK , 0.488193909859941_RK , -0.177375156618825_RK , -0.196053487807333_RK , 1.41931015064255_RK , 0.291584373984183_RK , 0.197811053464361_RK , 1.58769908997406_RK , -0.804465956349547_RK , 0.696624415849607_RK , 0.835088165072682_RK , -0.243715140377952_RK , 0.215670086403744_RK , -1.16584393148205_RK , -1.14795277889859_RK , 0.104874716016494_RK , 0.722254032225002_RK , 2.58549125261624_RK , -0.666890670701386_RK , 0.187331024578940_RK , -0.0824944253709554_RK , -1.93302291785099_RK , -0.438966153934773_RK , -1.79467884145512_RK ]
integer(IK), parameter lenDistSortedDiff = 200_IK
real(RK), dimension(*), parameter DistSortedDiff = [ 0.00137390044027030_RK , 0.00106568311889532_RK , 0.00261528537896705_RK , 0.00418324458049812_RK , 0.00173791427946435_RK , 0.00683744981995738_RK , 0.00122509129524828_RK , 0.000963897105374811_RK , 0.00659617936766466_RK , 0.00121099678988135_RK , 0.00152627239164915_RK , 5.59784103162375e-05_RK , 0.00396276701851184_RK , 0.00585926454186925_RK , 0.00183541725616831_RK , 0.00213464221769843_RK , 0.00456380640221332_RK , 0.000300222645855053_RK , 0.00113346207247378_RK , 0.00403412924770930_RK , 0.00876326613184120_RK , 0.00240591898034481_RK , 0.00111791498744240_RK , 0.000314496869014858_RK , 0.00166278866932723_RK , 0.00123356868877644_RK , 0.00136174700279745_RK , 0.00180033865772067_RK , 0.000188696505842079_RK , 0.00447901518516258_RK , 0.000649229339662938_RK , 0.00665965285198666_RK , 0.000639392345076595_RK , 0.00439231287788411_RK , 0.00514580427373124_RK , 0.00325615977507276_RK , 0.00262444209665191_RK , 0.00287172623926713_RK , 0.00726524941509710_RK , 0.000679801673850622_RK , 0.000771848959060684_RK , 0.00236687990071305_RK , 0.00279738279147568_RK , 0.00134507052319155_RK , 0.00192351678728353_RK , 0.000403579255582320_RK , 0.00466075625864260_RK , 0.00128562661588161_RK , 0.00240934864593989_RK , 0.00379834817045643_RK , 0.00626106613651900_RK , 0.00155470502430244_RK , 0.00386451831278178_RK , 0.00633652247623751_RK , 0.00212716547361247_RK , 0.000117519040001346_RK , 0.00268124387647972_RK , 0.00330190345409753_RK , 0.00181556281964235_RK , 0.00680782445764760_RK , 0.00344385667182678_RK , 0.00341876847109601_RK , 0.00156480476836285_RK , 0.00392916582362890_RK , 0.000536610168473173_RK , 0.00308379345606979_RK , 0.00382371993615627_RK , 0.00143530941667058_RK , 0.000273761654861704_RK , 0.000218939488190961_RK , 0.00395298813907463_RK , 0.00461683348784969_RK , 0.000587765974902510_RK , 0.00130109023546354_RK , 0.000446086978761473_RK , 0.00102849200817856_RK , 0.00475349511066359_RK , 0.00177004768590394_RK , 0.00118757227387534_RK , 0.00511260207997721_RK , 0.000966468749441840_RK , 0.00153506873793674_RK , 0.000163947408605591_RK , 0.00159865940856585_RK , 0.00319324233871277_RK , 0.00182318600045628_RK , 0.00270039749021500_RK , 0.00233393067978271_RK , 0.000304246250464657_RK , 0.00107643657879242_RK , 0.00149167058888822_RK , 3.22029433108551e-05_RK , 0.000507552164931036_RK , 0.00284976448963692_RK , 0.00261297396275373_RK , 0.00115230561975765_RK , 0.000589761776301434_RK , 0.00254655116972891_RK , 0.000736372303162147_RK , 0.00298938200986687_RK , 0.00115908892632211_RK , 0.0118304957984586_RK , 0.00427409203243478_RK , 0.00408018550920808_RK , 0.00137769679358790_RK , 0.00172460242999972_RK , 0.000397268483832813_RK , 0.00640511077756611_RK , 0.00160078461814450_RK , 0.00116751842007934_RK , 0.00689243594329803_RK , 5.96420573087952e-05_RK , 0.00120353557763264_RK , 0.00542771429675204_RK , 0.00610071142686630_RK , 0.00213356732282444_RK , 0.000281572449424172_RK , 0.00129330702548425_RK , 0.000169205982398446_RK , 0.000101693454083507_RK , 0.000396590512815487_RK , 0.000271783190621933_RK , 0.00207176434429135_RK , 0.00195525703558364_RK , 0.00133407286142151_RK , 0.00146450204323612_RK , 0.00172854780161391_RK , 0.00175309009682001_RK , 0.00591372011950542_RK , 0.00383246845630059_RK , 0.00478224831434315_RK , 0.00140155544663756_RK , 0.00311278264609216_RK , 0.00117361727622267_RK , 0.00197417012646872_RK , 0.00124210536927416_RK , 0.000362752683200629_RK , 0.000939106199745576_RK , 0.000794249402029323_RK , 0.000913827979191928_RK , 0.00720437268872554_RK , 0.000205371175825086_RK , 0.00715773811743015_RK , 0.00251452853672052_RK , 0.000861445629684599_RK , 0.00418790413483983_RK , 0.000370461989028015_RK , 0.00125679370708720_RK , 0.00349303438590243_RK , 0.000724203659035916_RK , 0.000491862014471267_RK , 0.00287196585168448_RK , 0.00185611717084277_RK , 0.000150069773691919_RK , 0.000848534416059033_RK , 0.00123442270407526_RK , 0.00103148223612315_RK , 0.00132400045208614_RK , 0.00435456041987981_RK , 0.00117222896204028_RK , 0.000873409715677065_RK , 0.00512459761807316_RK , 0.000423255105326148_RK , 0.00801979475421000_RK , 0.00452332834787750_RK , 0.000662717679231761_RK , 0.00612674945114589_RK , 0.000241023672676199_RK , 0.00241368458759861_RK , 0.00721401234545482_RK , 0.000617822886748609_RK , 4.20361472183162e-05_RK , 0.000176033863938718_RK , 0.00261140736592547_RK , 0.00161441323061740_RK , 0.00119563944997603_RK , 0.000161186670205815_RK , 0.00186893825670897_RK , 0.0156568954429827_RK , 0.00333188871092183_RK , 0.00460140509714901_RK , 0.00106350049875970_RK , 0.000278484374323207_RK , 0.000109843896551887_RK , 0.00517794656024040_RK , 0.000764568679501587_RK , 0.00106947825226744_RK , 0.00475394751147906_RK , 0.00700310227105183_RK , 0.00280107346803815_RK , 0.00594747756623304_RK , 0.00268586958531547_RK , 0.00120417364527792_RK , 0.00344542024642325_RK , 0.00217032516670990_RK , 0.00170145556378476_RK , 0.00159968663729304_RK , 0.00153233985478085_RK , 0.00219750724001799_RK , 0.00230064745992042_RK ]
integer(IK), dimension(*), parameter SampleSize = [ 1_IK , 101_IK , 102_IK , 103_IK , 104_IK , 105_IK , 106_IK , 107_IK , 108_IK , 109_IK , 110_IK ]
integer(IK), parameter lenSampleSize = size(SampleSize, kind=IK)
real(RK), dimension(*), parameter ProbKS_REF = [ 1._RK , 0.482474176998994_RK , 0.370817196700337_RK , 0.493146633387423_RK , 0.702120402082310_RK , 0.671010642014021_RK , 0.713612126474551_RK , 0.683487750289677_RK , 0.559321682773637_RK , 0.530113153332594_RK , 0.571577075807556_RK ]
real(RK), dimension(*), parameter StatKS_REF = [ 0._RK , 0.162352941176471_RK , 0.176470588235294_RK , 0.159502262443439_RK , 0.134615384615385_RK , 0.137518142235123_RK , 0.132075471698113_RK , 0.134870719776380_RK , 0.148148148148148_RK , 0.150841750841751_RK , 0.145454545454545_RK ]
Detailed Description
This module contains tests of the module pm_statest.
Author:
Amir Shahmoradi
Function/Subroutine Documentation
setTest()
subroutine test_pm_statest::setTest
Definition at line 433 of file test_pm_hypoTest.F90.
References test_Uniformity().
test_doKS1_1()
logical(LK) function test_pm_statest::test_doKS1_1
Definition at line 451 of file test_pm_hypoTest.F90.
References pm_kind::IK, and pm_kind::RK.
test_doSortedKS2_1()
logical(LK) function test_pm_statest::test_doSortedKS2_1
Definition at line 636 of file test_pm_hypoTest.F90.
References pm_kind::IK, and pm_kind::RK.
test_doUniformKS1_1()
logical(LK) function test_pm_statest::test_doUniformKS1_1
Definition at line 583 of file test_pm_hypoTest.F90.
References pm_kind::IK, and pm_kind::RK.
test_getCumDenComKS_1()
logical(LK) function test_pm_statest::test_getCumDenComKS_1
Definition at line 514 of file test_pm_hypoTest.F90.
References pm_kind::IK, and pm_kind::RK.
test_getSampleDisparity_1()
logical(LK) function test_pm_statest::test_getSampleDisparity_1
Any value of SampleSize smaller than one or larger than the size of the input Point should lead to an error.
Definition at line 702 of file test_pm_hypoTest.F90.
References pm_kind::IK, and pm_kind::RK.
test_getSampleDisparity_2()
logical(LK) function test_pm_statest::test_getSampleDisparity_2
Any value of SampleSize smaller than one or larger than the size of the input Point should lead to an error.
Definition at line 736 of file test_pm_hypoTest.F90.
References pm_kind::IK, and pm_kind::RK.
test_performance_1()
logical(LK) function test_pm_statest::test_performance_1
Compare performance of getCumDenComKS()` with pm_statest::getProbKS(). Results indicated that pm_statest::getProbKS() is approximately 2-3 times faster.
Definition at line 547 of file test_pm_hypoTest.F90.
References pm_kind::IK, and pm_kind::RK.
test_Uniformity()
subroutine test_pm_statest::test_Uniformity
Definition at line 793 of file test_pm_hypoTest.F90.
References doAutoKS(), doCrossKS(), pm_distanceEuclid::euclidsq, pm_distanceEuclid::euclidu, pm_kind::IK, pm_kind::LK, pm_kind::RK, and pm_kind::RKS.
Referenced by setTest().
Variable Documentation
DistSortedDiff
real(RK), dimension(*), parameter test_pm_statest::DistSortedDiff = [ 0.00137390044027030_RK , 0.00106568311889532_RK , 0.00261528537896705_RK , 0.00418324458049812_RK , 0.00173791427946435_RK , 0.00683744981995738_RK , 0.00122509129524828_RK , 0.000963897105374811_RK , 0.00659617936766466_RK , 0.00121099678988135_RK , 0.00152627239164915_RK , 5.59784103162375e-05_RK , 0.00396276701851184_RK , 0.00585926454186925_RK , 0.00183541725616831_RK , 0.00213464221769843_RK , 0.00456380640221332_RK , 0.000300222645855053_RK , 0.00113346207247378_RK , 0.00403412924770930_RK , 0.00876326613184120_RK , 0.00240591898034481_RK , 0.00111791498744240_RK , 0.000314496869014858_RK , 0.00166278866932723_RK , 0.00123356868877644_RK , 0.00136174700279745_RK , 0.00180033865772067_RK , 0.000188696505842079_RK , 0.00447901518516258_RK , 0.000649229339662938_RK , 0.00665965285198666_RK , 0.000639392345076595_RK , 0.00439231287788411_RK , 0.00514580427373124_RK , 0.00325615977507276_RK , 0.00262444209665191_RK , 0.00287172623926713_RK , 0.00726524941509710_RK , 0.000679801673850622_RK , 0.000771848959060684_RK , 0.00236687990071305_RK , 0.00279738279147568_RK , 0.00134507052319155_RK , 0.00192351678728353_RK , 0.000403579255582320_RK , 0.00466075625864260_RK , 0.00128562661588161_RK , 0.00240934864593989_RK , 0.00379834817045643_RK , 0.00626106613651900_RK , 0.00155470502430244_RK , 0.00386451831278178_RK , 0.00633652247623751_RK , 0.00212716547361247_RK , 0.000117519040001346_RK , 0.00268124387647972_RK , 0.00330190345409753_RK , 0.00181556281964235_RK , 0.00680782445764760_RK , 0.00344385667182678_RK , 0.00341876847109601_RK , 0.00156480476836285_RK , 0.00392916582362890_RK , 0.000536610168473173_RK , 0.00308379345606979_RK , 0.00382371993615627_RK , 0.00143530941667058_RK , 0.000273761654861704_RK , 0.000218939488190961_RK , 0.00395298813907463_RK , 0.00461683348784969_RK , 0.000587765974902510_RK , 0.00130109023546354_RK , 0.000446086978761473_RK , 0.00102849200817856_RK , 0.00475349511066359_RK , 0.00177004768590394_RK , 0.00118757227387534_RK , 0.00511260207997721_RK , 0.000966468749441840_RK , 0.00153506873793674_RK , 0.000163947408605591_RK , 0.00159865940856585_RK , 0.00319324233871277_RK , 0.00182318600045628_RK , 0.00270039749021500_RK , 0.00233393067978271_RK , 0.000304246250464657_RK , 0.00107643657879242_RK , 0.00149167058888822_RK , 3.22029433108551e-05_RK , 0.000507552164931036_RK , 0.00284976448963692_RK , 0.00261297396275373_RK , 0.00115230561975765_RK , 0.000589761776301434_RK , 0.00254655116972891_RK , 0.000736372303162147_RK , 0.00298938200986687_RK , 0.00115908892632211_RK , 0.0118304957984586_RK , 0.00427409203243478_RK , 0.00408018550920808_RK , 0.00137769679358790_RK , 0.00172460242999972_RK , 0.000397268483832813_RK , 0.00640511077756611_RK , 0.00160078461814450_RK , 0.00116751842007934_RK , 0.00689243594329803_RK , 5.96420573087952e-05_RK , 0.00120353557763264_RK , 0.00542771429675204_RK , 0.00610071142686630_RK , 0.00213356732282444_RK , 0.000281572449424172_RK , 0.00129330702548425_RK , 0.000169205982398446_RK , 0.000101693454083507_RK , 0.000396590512815487_RK , 0.000271783190621933_RK , 0.00207176434429135_RK , 0.00195525703558364_RK , 0.00133407286142151_RK , 0.00146450204323612_RK , 0.00172854780161391_RK , 0.00175309009682001_RK , 0.00591372011950542_RK , 0.00383246845630059_RK , 0.00478224831434315_RK , 0.00140155544663756_RK , 0.00311278264609216_RK , 0.00117361727622267_RK , 0.00197417012646872_RK , 0.00124210536927416_RK , 0.000362752683200629_RK , 0.000939106199745576_RK , 0.000794249402029323_RK , 0.000913827979191928_RK , 0.00720437268872554_RK , 0.000205371175825086_RK , 0.00715773811743015_RK , 0.00251452853672052_RK , 0.000861445629684599_RK , 0.00418790413483983_RK , 0.000370461989028015_RK , 0.00125679370708720_RK , 0.00349303438590243_RK , 0.000724203659035916_RK , 0.000491862014471267_RK , 0.00287196585168448_RK , 0.00185611717084277_RK , 0.000150069773691919_RK , 0.000848534416059033_RK , 0.00123442270407526_RK , 0.00103148223612315_RK , 0.00132400045208614_RK , 0.00435456041987981_RK , 0.00117222896204028_RK , 0.000873409715677065_RK , 0.00512459761807316_RK , 0.000423255105326148_RK , 0.00801979475421000_RK , 0.00452332834787750_RK , 0.000662717679231761_RK , 0.00612674945114589_RK , 0.000241023672676199_RK , 0.00241368458759861_RK , 0.00721401234545482_RK , 0.000617822886748609_RK , 4.20361472183162e-05_RK , 0.000176033863938718_RK , 0.00261140736592547_RK , 0.00161441323061740_RK , 0.00119563944997603_RK , 0.000161186670205815_RK , 0.00186893825670897_RK , 0.0156568954429827_RK , 0.00333188871092183_RK , 0.00460140509714901_RK , 0.00106350049875970_RK , 0.000278484374323207_RK , 0.000109843896551887_RK , 0.00517794656024040_RK , 0.000764568679501587_RK , 0.00106947825226744_RK , 0.00475394751147906_RK , 0.00700310227105183_RK , 0.00280107346803815_RK , 0.00594747756623304_RK , 0.00268586958531547_RK , 0.00120417364527792_RK , 0.00344542024642325_RK , 0.00217032516670990_RK , 0.00170145556378476_RK , 0.00159968663729304_RK , 0.00153233985478085_RK , 0.00219750724001799_RK , 0.00230064745992042_RK ]
Definition at line 188 of file test_pm_hypoTest.F90.
lenDistSortedDiff
integer(IK), parameter test_pm_statest::lenDistSortedDiff = 200_IK
Definition at line 187 of file test_pm_hypoTest.F90.
lenRnd
integer(IK), parameter test_pm_statest::lenRnd = 50_IK
Definition at line 32 of file test_pm_hypoTest.F90.
lenSampleSize
integer(IK), parameter test_pm_statest::lenSampleSize = size(SampleSize, kind=IK)
Definition at line 401 of file test_pm_hypoTest.F90.
ProbKS_REF
real(RK), dimension(*), parameter test_pm_statest::ProbKS_REF = [ 1._RK , 0.482474176998994_RK , 0.370817196700337_RK , 0.493146633387423_RK , 0.702120402082310_RK , 0.671010642014021_RK , 0.713612126474551_RK , 0.683487750289677_RK , 0.559321682773637_RK , 0.530113153332594_RK , 0.571577075807556_RK ]
Definition at line 402 of file test_pm_hypoTest.F90.
SampleSize
integer(IK), dimension(*), parameter test_pm_statest::SampleSize = [ 1_IK , 101_IK , 102_IK , 103_IK , 104_IK , 105_IK , 106_IK , 107_IK , 108_IK , 109_IK , 110_IK ]
Definition at line 389 of file test_pm_hypoTest.F90.
StatKS_REF
real(RK), dimension(*), parameter test_pm_statest::StatKS_REF = [ 0._RK , 0.162352941176471_RK , 0.176470588235294_RK , 0.159502262443439_RK , 0.134615384615385_RK , 0.137518142235123_RK , 0.132075471698113_RK , 0.134870719776380_RK , 0.148148148148148_RK , 0.150841750841751_RK , 0.145454545454545_RK ]
Definition at line 414 of file test_pm_hypoTest.F90.
StdNormRnd1
real(RK), dimension(lenRnd) test_pm_statest::StdNormRnd1 = [ 0.537667139546100_RK , 1.83388501459509_RK , -2.25884686100365_RK , 0.862173320368121_RK , 0.318765239858981_RK , -1.30768829630527_RK , -0.433592022305684_RK , 0.342624466538650_RK , 3.57839693972576_RK , 2.76943702988488_RK , -1.34988694015652_RK , 3.03492346633185_RK , 0.725404224946106_RK , -0.0630548731896562_RK , 0.714742903826096_RK , -0.204966058299775_RK , -0.124144348216312_RK , 1.48969760778547_RK , 1.40903448980048_RK , 1.41719241342961_RK , 0.671497133608081_RK , -1.20748692268504_RK , 0.717238651328839_RK , 1.63023528916473_RK , 0.488893770311789_RK , 1.03469300991786_RK , 0.726885133383238_RK , -0.303440924786016_RK , 0.293871467096658_RK , -0.787282803758638_RK , 0.888395631757642_RK , -1.14707010696915_RK , -1.06887045816803_RK , -0.809498694424876_RK , -2.94428416199490_RK , 1.43838029281510_RK , 0.325190539456198_RK , -0.754928319169703_RK , 1.37029854009523_RK , -1.71151641885370_RK , -0.102242446085491_RK , -0.241447041607358_RK , 0.319206739165502_RK , 0.312858596637428_RK , -0.864879917324457_RK , -0.0300512961962686_RK , -0.164879019209038_RK , 0.627707287528727_RK , 1.09326566903948_RK , 1.10927329761440_RK ]
Definition at line 85 of file test_pm_hypoTest.F90.
StdNormRnd2
real(RK), dimension(lenRnd) test_pm_statest::StdNormRnd2 = [ -0.863652821988714_RK , 0.0773590911304249_RK , -1.21411704361541_RK , -1.11350074148676_RK , -0.00684932810334806_RK , 1.53263030828475_RK , -0.769665913753682_RK , 0.371378812760058_RK , -0.225584402271252_RK , 1.11735613881447_RK , -1.08906429505224_RK , 0.0325574641649735_RK , 0.552527021112224_RK , 1.10061021788087_RK , 1.54421189550395_RK , 0.0859311331754255_RK , -1.49159031063761_RK , -0.742301837259857_RK , -1.06158173331999_RK , 2.35045722400204_RK , -0.615601881466894_RK , 0.748076783703985_RK , -0.192418510588264_RK , 0.888610425420721_RK , -0.764849236567874_RK , -1.40226896933876_RK , -1.42237592509150_RK , 0.488193909859941_RK , -0.177375156618825_RK , -0.196053487807333_RK , 1.41931015064255_RK , 0.291584373984183_RK , 0.197811053464361_RK , 1.58769908997406_RK , -0.804465956349547_RK , 0.696624415849607_RK , 0.835088165072682_RK , -0.243715140377952_RK , 0.215670086403744_RK , -1.16584393148205_RK , -1.14795277889859_RK , 0.104874716016494_RK , 0.722254032225002_RK , 2.58549125261624_RK , -0.666890670701386_RK , 0.187331024578940_RK , -0.0824944253709554_RK , -1.93302291785099_RK , -0.438966153934773_RK , -1.79467884145512_RK ]
Definition at line 136 of file test_pm_hypoTest.F90.
test
type(test_type) test_pm_statest::test
Definition at line 30 of file test_pm_hypoTest.F90.
UnifRnd
real(RK), dimension(lenRnd) test_pm_statest::UnifRnd = [ 0.0759666916908419_RK , 0.2399161535536580_RK , 0.1233189348351660_RK , 0.1839077882824170_RK , 0.2399525256649030_RK , 0.4172670690843700_RK , 0.0496544303257421_RK , 0.9027161099152810_RK , 0.9447871897216460_RK , 0.4908640924680800_RK , 0.4892526384000190_RK , 0.3377194098213770_RK , 0.9000538464176620_RK , 0.3692467811202150_RK , 0.1112027552937870_RK , 0.7802520683211380_RK , 0.3897388369612530_RK , 0.2416912859138330_RK , 0.4039121455881150_RK , 0.0964545251683886_RK , 0.1319732926063350_RK , 0.9420505907754850_RK , 0.9561345402298020_RK , 0.5752085950784660_RK , 0.0597795429471558_RK , 0.2347799133724060_RK , 0.3531585712220710_RK , 0.8211940401979590_RK , 0.0154034376515551_RK , 0.0430238016578078_RK , 0.1689900294627040_RK , 0.6491154749564520_RK , 0.7317223856586700_RK , 0.6477459631363070_RK , 0.4509237064309450_RK , 0.5470088922863450_RK , 0.2963208056077730_RK , 0.7446928070741560_RK , 0.1889550150325450_RK , 0.6867754333653150_RK , 0.1835111557372700_RK , 0.3684845964903370_RK , 0.6256185607296900_RK , 0.7802274351513770_RK , 0.0811257688657853_RK , 0.9293859709687300_RK , 0.7757126786084020_RK , 0.4867916324031720_RK , 0.4358585885809190_RK , 0.4467837494298060_RK ]
Definition at line 34 of file test_pm_hypoTest.F90.