ParaMonte Fortran 2.0.0: pm_arrayReplace Module Reference
pm_arrayReplace Module Reference
This module contains procedures and generic interfaces for replacing patterns within arrays of various types.
Data Types
interface getReplaced
Generate and return an arrayNew of the same type and kind as the input array, in which the requested instances of the input pattern have been replaced with the input replacement.
interface setReplaced
Replace the requested instances of the input pattern with the input replacement in the allocatable input/output array.
Functions/Subroutines
pure recursive character(:, SK) function, allocatable getReplaced_recurs_alloc (array, pattern, replacement)
[LEGACY code]
Generate and return a copy of the input array where all instances of the input pattern in it are replaced with the input replacement.
Variables
character(*, SK), parameter MODULE_NAME = "@pm_arrayReplace"
Detailed Description
This module contains procedures and generic interfaces for replacing patterns within arrays of various types.
Benchmarks:
Benchmark :: The runtime performance of getReplaced vs. setReplaced ⛓
! Test the performance of `getReplaced()` vs. `setReplaced()`.
program benchmark
    use iso_fortran_env, only: error_unit
    use pm_kind, only: IK, LK, RK, SK
    use pm_bench, only: bench_type
    implicit none
    integer(IK)                         :: i
    integer(IK)                         :: isize
    integer(IK)                         :: fileUnit
    integer(IK) , parameter             :: NSIZE = 12_IK
    integer(IK) , parameter             :: NBENCH = 3_IK
    integer(IK)                         :: arraySize(NSIZE)
    logical(LK)                         :: dummy = .true._LK
    character(:, SK), allocatable       :: array
    character(*, SK), parameter         :: pattern = "a"
    character(*, SK), parameter         :: Replacement = "**"
    type(bench_type)                    :: bench(NBENCH)
    bench(1) = bench_type(name = SK_"setReplaced", exec = setReplaced , overhead = setOverhead)
    bench(2) = bench_type(name = SK_"getReplaced", exec = getReplaced , overhead = setOverhead)
    bench(3) = bench_type(name = SK_"getReplaced_recurs_alloc", exec = getReplaced_recurs_alloc , overhead = setOverhead)
    arraySize = [( 2_IK**isize, isize = 1_IK, NSIZE )]
    write(*,"(*(g0,:,' '))")
    write(*,"(*(g0,:,' '))") "setReplaced() vs. getReplaced() vs. getReplaced_recurs_alloc()"
    write(*,"(*(g0,:,' '))")
    open(newunit = fileUnit, file = "main.out", status = "replace")
        write(fileUnit, "(*(g0,:,','))") "arraySize", (bench(i)%name, i = 1, NBENCH)
        loopOverArraySize: do isize = 1, NSIZE
            write(*,"(*(g0,:,' '))") "Benchmarking with size", arraySize(isize)
            do i = 1, NBENCH
                bench(i)%timing = bench(i)%getTiming(minsec = 0.05_RK)
            end do
            write(fileUnit,"(*(g0,:,','))") arraySize(isize), (bench(i)%timing%mean, i = 1, NBENCH)
        end do loopOverArraySize
        write(*,"(*(g0,:,' '))") dummy
        write(*,"(*(g0,:,' '))")
    close(fileUnit)
contains
    !%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    ! procedure wrappers.
    !%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    subroutine setOverhead()
        call initialize()
        call finalize()
    end subroutine
    subroutine initialize()
        allocate( character(arraySize(isize)) :: array )
        !block
        !    use pm_distUnif, only: setUnifRand
        !    call setUnifRand(array)
        !end block
        block
            array(:) = repeat(pattern, len(array))
        end block
    end subroutine
    subroutine finalize()
        dummy = dummy .and. array(1:1) == pattern
        deallocate(array)
    end subroutine
    subroutine setReplaced()
        block
            use pm_arrayReplace, only: setReplaced
            call initialize()
            call setReplaced(array, pattern, Replacement)
            call finalize()
        end block
    end subroutine
    subroutine getReplaced()
        block
            use pm_arrayReplace, only: getReplaced
            call initialize()
            array = getReplaced(array, pattern, Replacement)
            call finalize()
        end block
    end subroutine
    subroutine getReplaced_recurs_alloc()
        block
            use pm_arrayReplace, only: getReplaced_recurs_alloc
            call initialize()
            array = getReplaced_recurs_alloc(array, pattern, Replacement)
            call finalize()
        end block
    end subroutine
end program benchmark
Example Unix compile command via Intel ifort compiler ⛓
#!/usr/bin/env sh
rm main.exe
ifort -fpp -standard-semantics -O3 -Wl,-rpath,../../../lib -I../../../inc main.F90 ../../../lib/libparamonte_fortran_*_intel* -o main.exe
./main.exe
Example Windows Batch compile command via Intel ifort compiler ⛓
del main.exe
set PATH=..\..\..\lib;%PATH%
ifort /fpp /standard-semantics /O3 /I:..\..\..\include main.F90 ..\..\..\lib\libparamonte_fortran_*_intel*.lib /exe:main.exe
main.exe
Example Unix / MinGW compile command via GNU gfortran compiler ⛓
#!/usr/bin/env sh
rm main.exe
gfortran -cpp -ffree-line-length-none -O3 -Wl,-rpath,../../../lib -I../../../inc main.F90 ../../../lib/libparamonte_fortran_*_gnu* -o main.exe
./main.exe
Postprocessing of the benchmark output ⛓
#!/usr/bin/env python
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
fontsize = 14
methods = ["setReplaced", "getReplaced", "getReplaced_recurs_alloc"]
df = pd.read_csv("main.out")
ax = plt.figure(figsize = 1.25 * np.array([6.4,4.6]), dpi = 200)
ax = plt.subplot()
for method in methods:
    plt.plot( df["arraySize"].values
            , df[method].values
            , linewidth = 2
            )
plt.xticks(fontsize = fontsize)
plt.yticks(fontsize = fontsize)
ax.set_xlabel("Array Size", fontsize = fontsize)
ax.set_ylabel("Runtime [ seconds ]", fontsize = fontsize)
ax.set_title("setReplaced() vs. getReplaced() vs. getReplaced_recurs_alloc()\nLower is better.", fontsize = fontsize)
ax.set_xscale("log")
ax.set_yscale("log")
plt.minorticks_on()
plt.grid(visible = True, which = "both", axis = "both", color = "0.85", linestyle = "-")
ax.tick_params(axis = "y", which = "minor")
ax.tick_params(axis = "x", which = "minor")
ax.legend   (methods
           #, loc='center left'
           #, bbox_to_anchor=(1, 0.5)
            , fontsize = fontsize
            )
plt.tight_layout()
plt.savefig("benchmark.getReplaced_vs_setReplaced.runtime.png")
ax = plt.figure(figsize = 1.25 * np.array([6.4,4.6]), dpi = 200)
ax = plt.subplot()
plt.plot(df["arraySize"].values
        , np.ones(len(df["arraySize"].values))
        , linestyle = "--"
       #, color = "black"
        , linewidth = 2
        )
plt.plot(df["arraySize"].values
        , df["getReplaced"].values / df["setReplaced"].values
        , linewidth = 2
        )
plt.plot(df["arraySize"].values
        , df["getReplaced_recurs_alloc"].values / df["setReplaced"].values
        , linewidth = 2
        )
plt.xticks(fontsize = fontsize)
plt.yticks(fontsize = fontsize)
ax.set_xlabel("Array Size", fontsize = fontsize)
ax.set_ylabel("Runtime compared to setReplaced()", fontsize = fontsize)
ax.set_title("getReplaced / setReplaced vs. getReplaced_recurs_alloc / setReplaced\nLower means faster. Lower than 1 means faster than setReplaced().", fontsize = fontsize)
ax.set_xscale("log")
#ax.set_yscale("log")
plt.minorticks_on()
plt.grid(visible = True, which = "both", axis = "both", color = "0.85", linestyle = "-")
ax.tick_params(axis = "y", which = "minor")
ax.tick_params(axis = "x", which = "minor")
ax.legend   (["setReplaced", "getReplaced", "getReplaced_recurs_alloc"]
           #, bbox_to_anchor = (1, 0.5)
           #, loc = "center left"
            , fontsize = fontsize
            )
plt.tight_layout()
plt.savefig("benchmark.getReplaced_vs_setReplaced.runtime.ratio.png")
Visualization of the benchmark output ⛓
Benchmark moral ⛓
The procedures under the generic interface getReplaced are functions while the procedures under the generic interface setReplaced are subroutines.
From the benchmark results, it appears that the functional interface performs slightly less efficiently than the subroutine interface.
Note that this benchmark does not even include the cost of repeated reallcations, that is, the allocation of Replaced happen only once in all tests.
Furthermore, the recursive getReplaced() implementation with recursive allocations appears to be 3-33 times slower than the subroutine implementation, depending on the size of the array within which the pattern is to be replaced.
Note that this benchmark considers the worst-case scenario where all elements of the input array match the input pattern and must be therefore, replaced.
See also
pm_arrayInsert
pm_arrayRemove
Test:
test_pm_arrayReplace
Final Remarks ⛓
If you believe this algorithm or its documentation can be improved, we appreciate your contribution and help to edit this page's documentation and source file on GitHub.
For details on the naming abbreviations, see this page.
For details on the naming conventions, see this page.
This software is distributed under the MIT license with additional terms outlined below.
If you use any parts or concepts from this library to any extent, you must acknowledge the usage by citing the relevant publications of the ParaMonte library.
If you regenerate any parts/ideas from this library in a programming environment other than those currently supported by this ParaMonte library (i.e., other than C, C++, Fortran, MATLAB, Python, R), you must also ask the end users to cite this original ParaMonte library.
Copyright
Computational Data Science Lab
Author:
Fatemeh Bagheri, Wednesday 12:20 AM, October 13, 2021, Dallas, TX
Function/Subroutine Documentation
getReplaced_recurs_alloc()
pure recursive character(:, SK) function, allocatable pm_arrayReplace::getReplaced_recurs_alloc (character(*, SK), intent(in) array, character(*, SK), intent(in) pattern, character(*, SK), intent(in) replacement)
[LEGACY code]
Generate and return a copy of the input array where all instances of the input pattern in it are replaced with the input replacement.
Parameters
[in] array : The input scalar character of default kind SK.
[in] pattern : The input scalar the same type and kind as the input array representing the pattern to be searched within array.
[in] replacement : The input scalar the same type and kind as the input array representing the replacement for instances of pattern in array.
Returns
arrayNew : The output copy of the input array where all instances of the input pattern in it are replaced with the input replacement.
Warning
This procedure is solely provided for benchmarking purposes to compare the performance difference between a naive recursive allocation method of replacement and the optimized method implemented under the generic interfaces in getReplaced and setReplaced.
Remarks
The procedures under discussion are pure.
The procedures under discussion are recursive.
See also
getReplaced
setReplaced
test_pm_arrayReplace
Final Remarks ⛓
If you believe this algorithm or its documentation can be improved, we appreciate your contribution and help to edit this page's documentation and source file on GitHub.
For details on the naming abbreviations, see this page.
For details on the naming conventions, see this page.
This software is distributed under the MIT license with additional terms outlined below.
If you use any parts or concepts from this library to any extent, you must acknowledge the usage by citing the relevant publications of the ParaMonte library.
If you regenerate any parts/ideas from this library in a programming environment other than those currently supported by this ParaMonte library (i.e., other than C, C++, Fortran, MATLAB, Python, R), you must also ask the end users to cite this original ParaMonte library.
Copyright
Computational Data Science Lab
Author:
Amir Shahmoradi, September 1, 2017, 12:00 AM, Institute for Computational Engineering and Sciences (ICES), The University of Texas at Austin
Definition at line 14612 of file pm_arrayReplace.F90.
References getReplaced_recurs_alloc(), and pm_kind::IK.
Referenced by getReplaced_recurs_alloc(), test_pm_arrayReplace::test_getReplaced_recurs_alloc_1(), test_pm_arrayReplace::test_getReplaced_recurs_alloc_2(), and test_pm_arrayReplace::test_getReplaced_recurs_alloc_3().
Variable Documentation
MODULE_NAME
character(*, SK), parameter pm_arrayReplace::MODULE_NAME = "@pm_arrayReplace"
Definition at line 60 of file pm_arrayReplace.F90.